### ISSUE TITLE
System32 so slow

### ISSUE THREAD

**Issue by tanaduda** [Cpasjuste/pemu#100]
Original Fbneo emulate it correctly

**Comment by Cpasjuste** [comment]
Hi,

Is this on switch or PS4 ?

**Comment by tanaduda** [comment]
Excuse me. PS4

**Comment by tatundria** [comment]
Switch too. Too slow

**Comment by Cpasjuste** [comment]
I'll take a closer look but the Linux build of pfbn does work fine too, so I guess it's maybe a problem of cpu speed (while it's strange on PS4..)

**Comment by tanaduda** [comment]
FBneo is a single core software, maybe 1.6ghz arent enough to run at full speed...

**Comment by tanaduda** [comment]
Thanks anyway!!
