### ISSUE TITLE
pFBN: Cannot access Service Menu on Switch

### ISSUE THREAD

**Issue by tatundria** [Cpasjuste/pemu#101]
Cannot access Service Menu neither in NeoGeo or MAME with the button combinations provided for Switch. If I press (-) + (+) I go straight to the emulator main menu. Any fix for this?

**Comment by tanaduda** [comment]
PS4 Too

**Comment by Cpasjuste** [comment]
Thanks for the report, I know how to fix this, will try to do it in the weekend.

**Comment by lineacero** [comment]
❤Wonderfull my friend❤

**Comment by Cpasjuste** [comment]
Hi, this should be fixed on latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.1
