### ISSUE TITLE
most cave and igs  games crash on ps4 pfbneo

### ISSUE THREAD

**Issue by tehrzky** [Cpasjuste/pemu#107]
ex. esplaguda 2, demon front

tnx

**Comment by tanaduda** [comment]
> ex. esplaguda 2, demon front
> 
> tnx

Did you checked your romset?

![image](https://user-images.githubusercontent.com/54275290/154550628-76886870-f9a2-4976-b707-8cd02c9acdcd.png)

![image](https://user-images.githubusercontent.com/54275290/154550705-902bcc11-25ac-4407-b31f-380d70deff29.png)

**Comment by Cpasjuste** [comment]
Hi,

I think this will be fixed in next release, which should come soon.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed on latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.1
