### ISSUE TITLE
Hacks roms PSNES PS4

### ISSUE THREAD

**Issue by vini-sousa** [Cpasjuste/pemu#109]
Any way to open hack roms?

I'm trying to play some super mario world hacks roms, but they don't show up in the games list

**Comment by Cpasjuste** [comment]
> Any way to open hack roms?
> 
> I'm trying to play some super mario world hacks roms, but they don't show up in the games list

Hi,

I think the ROMs should be listed if you have the "SHOW ALL" option enabled, isn't it ? Will try to take a closer look asap.

**Comment by Cpasjuste** [comment]
Hi, i'm not able to reproduce this problem, at least on latest release with "SHOW ZIP NAMES" enabled
