### ISSUE TITLE
Driver init failed on PS4 PFBneo with Demons of Asteborg Rom

### ISSUE THREAD

**Issue by ddylard** [Cpasjuste/pemu#110]
As the title says. Tried with 1.0 rom also 1.1 and 1.1 with fixed header for emulators.

**Comment by myfranco** [comment]
> Hi,
> 
> I think this will be fixed in next release, which should come soon.

Hi,
I'm using Pfbneo 5.0 on PS4PRO 9.00 JB but some of those games give "driver init failed" such as Tekken 3. Furthermore, i can see that you can run Metal Slug 4 but it doesn't work on me. It says emulation will likely have problems. Using default settings and all games are in roms folder.

**Comment by myfranco** [comment]
> Hi,
> 
> I think this will be fixed in next release, which should come soon.

Hi,
I'm using Pfbneo 5.0 on PS4PRO 9.00 JB but some of those games give "driver init failed" such as Tekken 3. Furthermore, i can see that you can run Metal Slug 4 but it doesn't work on me. It says emulation will likely have problems. Using default settings and all games are in roms folder.

**Comment by Cpasjuste** [comment]
I can confirm this will be fixed in next release, i'll close this when it's out.

**Comment by ddylard** [comment]
Great bro! I anxiously wait for it heheEl 21 feb. 2022 10:27 AM, Cpasjuste ***@***.***> escribió:
I can confirm this will be fixed in next release, i'll close this when it's out.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed on latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.1
