### ISSUE TITLE
Use in a commercial project 

### ISSUE THREAD

**Issue by ryanschott** [Cpasjuste/pemu#112]
We just acquired the license to an original NES title. We are doing a Cartridge release, but we would also like to offer the game on modern consoles. I am looking to contract a stripped down version of your software to make this happen. We could do a build ourselves, but feel that working with you would be the best way to put out a quality product. We are licensed developers on all modern consoles, and can offer support in addition to payment. Thank you.

**Comment by Cpasjuste** [comment]
> We just acquired the license to an original NES title. We are doing a Cartridge release, but we would also like to offer the game on modern consoles. I am looking to contract a stripped down version of your software to make this happen. We could do a build ourselves, but feel that working with you would be the best way to put out a quality product. We are licensed developers on all modern consoles, and can offer support in addition to payment. Thank you.

Hi,

This seems very exciting to me, and I thanks your for this opportunity. That said, there's a lot of parameters to handle for such a project, including licencing and such. You can contact me at cpasjuste@gmail.com if you wants to talk deeper about this.

Thanks,
cpasjuste
