### ISSUE TITLE
[PFBNeo 5.0 on switch]Crash screen issue in some MEGADRIVE and COMAD games.(not all megadrive games.)

### ISSUE THREAD

**Issue by DNFPoison2** [Cpasjuste/pemu#113]
Hi. I downloaded PFBN5.0 from Nintendo Switch and tested every games. Most of the games worked normally, but some games in MegaDrive and  COMAD was not good.

1. Some mega-drive games twist the screen. The twisted screen is similar to when the NTSC/PAL frequency is not correct.
The screen is normally output from all mega drive cores in Retroarch, and is also normally output from PFBNeo4.4.
(Example: Midnight Resistance JAP/USA)

2. The screen of some COMAD games is output 180 degrees inverted when the game is executed.

Check please.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed on latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.1
