### ISSUE TITLE
Faster soundtrack/voices md games

### ISSUE THREAD

**Issue by tanaduda** [Cpasjuste/pemu#115]
Pfbneo 5.1, PS4. 

Street champion, super street and streets of rage 2 has this issue. 
Tested sonic, streets of rage 2 and last battle, no problem

**Comment by Cpasjuste** [comment]
Hi @tanaduda,

Could you try with the "force 60hz" option off? It may solve the problem (I can't try it before tomorrow at least).

**Comment by tanaduda** [comment]
Disabling “force 60 hz” solved the problem

**Comment by Cpasjuste** [comment]
Yeah it's what I thought. You have this problem with PAL/50hz ROMs, so when force 60hz is enabled it runs too fast.
