### ISSUE TITLE
How to add more than 1 path to config.cfg?

### ISSUE THREAD

**Issue by jvhellraiser** [Cpasjuste/pemu#116]
Is it possible? i been trying this for a while without any progress help?
by the way i should mention i am trying this with Yuzu for every single emulator
that is pnes,psnes i get  1 config file that is config.cfg inside.
you get:

CONFIG : 
{
  VERSION = 501;
  ROMS_PATHS : 
  {
    ROMS_PATH0 = "/roms/";
  };
  
  Since Yuzu don't have a switch folder but it has a sdmc that is the same as the sdcard
  emulators made for the switch work pretty good on Yuzu but configuring path of each
  roms folder for every single emulator is a bit annoying foe me i am saying, so i would like to 
  understand how to add paths to the config.cfg,
  
  maybe is :
  CONFIG : 
{
  VERSION = 501;
  ROMS_PATHS : 
  {
    ROMS_PATH0 = "/roms/nes";
    ROMS_PATH1 = "/roms/snes";
  };
  
  but no the pnes keeps opening without reading the path giving same for the psnes
  maybe i am adding the path wrong maybe is :
  
   CONFIG : 
{
  VERSION = 501;
  ROMS_PATHS : 
  {
    ROMS_PATH0 = "/roms/nes";
  {
    ROMS_PATH1 = "/roms/snes";
  };
  
  and i could be wrong again so yeah how can make
  psnes and pnes work together and read there on path giving in the roms folder.

**Comment by Cpasjuste** [comment]
Hi, this is currently not supported sorry. Also, config files have different options per emulator, they can't be shared right now.
