### ISSUE TITLE
pNES 5.1 and pSNES 5.1. - no config modified?

### ISSUE THREAD

**Issue by spotanjo3** [Cpasjuste/pemu#117]
Only .nro ? Whats happened to zip with config ? I prefer to have my own background and such like you usually allowed us. And keep up the good work.

**Comment by Cpasjuste** [comment]
Hi,

you can download a skin in this repo (for example [here](https://github.com/Cpasjuste/pemu/tree/master/pfbneo/data/common/romfs/skins/default), edit then put the folder in emulator data directory (for example "/switch/pfba/skins/default" for pfbneo). This will override default skin.
