### ISSUE TITLE
pSNES 5.1 [Switch] - Roms from other regions than US (i.e. Europe, Japan) won't launch

### ISSUE THREAD

**Issue by sir-clan** [Cpasjuste/pemu#120]
In pSNES 5.1 PAL roms won't start as the loading bar is then stuck at 100% and pSNES does not react anymore. In pSNES 5.0, those roms have started at least, but had the faulty sound (50Hz bug). Please have this one fixed, it would be highly appreciated.

**Comment by AlbertoDiazC** [comment]
Same here

**Comment by Cpasjuste** [comment]
Thanks for the report, this is fixed and will be available soon.

**Comment by sir-clan** [comment]
Thanks for the quick reply and action. Keep up the great work!

**Comment by Bortoloti01** [comment]
The same is happening with the ps4

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.2
Please report here if this is not the case!
