### ISSUE TITLE
In the psnes 5.1 switch version, there is a problem with the sound sometimes bouncing.

### ISSUE THREAD

**Issue by brunohwas** [Cpasjuste/pemu#122]
It seems to be an occasional symptom. I felt it while playing in seiken densetsu 3. It would be perfect if only the sound problem was solved. I love the new shader feature. Thank you so much always.

**Comment by Cpasjuste** [comment]
Hi,

It will be fixed in next release, I hope this weekend.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.2
Please report here if this is not the case!
