### ISSUE TITLE
pfbneo: game not detected X-Men (Konami Beat`em up) 

### ISSUE THREAD

**Issue by tatundria** [Cpasjuste/pemu#123]
I cannot get the game X-Men (Konami Beat`em up) to being detected by the emulator. The romset is correct and it appears one more game in the initial counter when I load pFBNeo, but after that the game does not appear on the list. Please, any fix for this?

**Comment by Cpasjuste** [comment]
Hi,
I can confirm the problem, which is a problem with wrong clone assignment in the gamelist (if you enable show clones you should see them). It will be fixed in next relase.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.2
Please report here if this is not the case!
