### ISSUE TITLE
Vita pSNES - no subfolders or multiple ROM paths

### ISSUE THREAD

**Issue by npaladin2000** [Cpasjuste/pemu#127]
Not sure how high a priority this is, but it looks like pSNES on Vita is unable to automatically scan subfolders of the configured path. It's also unable to accempt multiple ROM paths. Normally this wouldn't be an issue but I'm trying to do MSU1 sets, and it gets pretty messy to put everything in one folder.

**Comment by Cpasjuste** [comment]
Hi,

I'm sorry this is not currently supported (and not planned for now) because on how gamelist are handled. I may take a look in the future..
