### ISSUE TITLE
A great cpasjuste emulator

### ISSUE THREAD

**Issue by Vecinagamer** [Cpasjuste/pemu#132]
In the pfneo emulator for Psvita it is a great emulator,,I registered to communicate it.
But R-type, R-type 2 and R-type Leo games are very slow in the game, if you could watch it, I would love to play it on your great emulator so good.

Pd:Vertical games, 1942, 1943 etc cannot be played because the controls are reversed.
In "Flip" rotation you can redefine the crosshead and it works, but the ideal is to redefine the  joycon 
on the right side of the console in "Off" rotation to be able to play vertical games well.
Thank you cpasjuste

**Comment by Cpasjuste** [comment]
Hi,

I think this should be fixed in [version 6.0](https://github.com/Cpasjuste/pemu/releases/tag/v6.0), can you confirm this ?

**Comment by Vecinagamer** [comment]
Perfect, rotating the games works, great, congratulations
