### ISSUE TITLE
pfbn switch favorite list clone rom add error

### ISSUE THREAD

**Issue by kabihuni** [Cpasjuste/pemu#134]
1. sf2 main rom favorite list add 
2. sf2 clone rom favorite list add
3. sf2 main rom swap

**Comment by Cpasjuste** [comment]
Hi,

I think this should be fixed in [version 6.0](https://github.com/Cpasjuste/pemu/releases/tag/v6.0), can you confirm this ?

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
