### ISSUE TITLE
psnes Vita - performance

### ISSUE THREAD

**Issue by npaladin2000** [Cpasjuste/pemu#135]
This is more an information thing, not sure if it's do-able but I'm noticing MSU-1 SNES ROMs are at the very edge of what the emulator can handle, any filters or options like that can take it over the edge. If it's possible to get soem tweaks and/or optimizations implemented for SNES performance on Vita it might help quite a bit. 

One example might be that there's no option for EFFECT: NONE. I assume all of those effects take a few extra CPU cycles,  being able to not have one at all might save an FPS or two.

**Comment by Vecinagamer** [comment]
no option for EFFECT: NONE,,,,It is the problem of slow games.

**Comment by Cpasjuste** [comment]
Hi,

I don't think this will be easily fixable as latest snes9x releases are very demanding for the vita... sorry.
