### ISSUE TITLE
(Switch) PFBNEO Allow to play TATE mode without detaching joycon (similar to how it works with the VITA) (ver. 5.2)

### ISSUE THREAD

**Issue by ertaboy356b** [Cpasjuste/pemu#137]
I set the ROTATION function to Flip then tried mapping the dpad to the right analog stick but the plane moves diagonally instead of the actual movement. It must be an issue where the actual dpad of the left joycon is interferring with the movement.

Tested game: Battle Bakraid

How to Reproduce:
 - Run Battle Bakraid rom
 - Set the rotation to FLIP
 - Set up the Right Analog as "left" as UP, "right" as DOWN, "up" as "RIGHT", and "down" as LEFT
 - Move the plane around and you'll see that instead of "UP" for example, it move diagonally instead.

**Comment by Vecinagamer** [comment]
I also have this problem,,, I can not play the games vertically and the controls are inverted.

**Comment by ertaboy356b** [comment]
Works fine on Flip. I think this issue is now resolved. Thanks!.
