### ISSUE TITLE
Custom game database db.xml

### ISSUE THREAD

**Issue by FlawFinder1** [Cpasjuste/pemu#142]
Hello, I'm using PSNES on switch downloaded from the Homebrew Appstore rather than from here. I'm using Atmosphere 1.3.1 an firmware 14.1.0, both being the latest. In an earlier version I was able to use gamelist.xml to use a custom gamelist. This was very useful for playing Super Mario World Mods. I skipped a few updates, but after reading it seems it was changed to db.xml at some point, but even after changing the name of my custom list to db.xml I'm unable to get it to work how it used to and instead only have the stock list of games. Is there a way to get db.xml or gamelist.xml to work again?

**Comment by Cpasjuste** [comment]
Hi,

The gamelist.xml is now embedded in romfs. You should be able to put a "gamelist.xml" file in data directory (/switch/psnes/gamelist.xml) that will override romfs one.

If it's not working then it's a bug, I'll fix that for next release (and should add a note about that in readme).

**Comment by Cpasjuste** [comment]
Ok, this is an error on my side : https://github.com/Cpasjuste/pemu/blob/577f96dc5a264b6fc92b9ff27e152aaee463d679/ui/c2dui_romlist.cpp#L79

Will fix that for next release.

**Comment by FlawFinder1** [comment]
Thank you, you've made a great homebrew and you even respond very quickly

**Comment by Vecinagamer** [comment]
Gracias, has hecho un gran homebrew

**Comment by Cpasjuste** [comment]
Hi,

I think this should be fixed in [version 6.0](https://github.com/Cpasjuste/pemu/releases/tag/v6.0), can you confirm this ?

**Comment by FlawFinder1** [comment]
I know others already reported that there's no games listed anymore, sorry, that probably happened because you were trying to add the ability to use custom gamelists back in. But since most people probably don't use custom lists I wanted to add that even with both gamelist.xml and db.xml I'm not seeing anything

**Comment by Cpasjuste** [comment]
Hi @FlawFinder1 , please take a look at this reply: https://github.com/Cpasjuste/pemu/issues/147#issuecomment-1119298954
To use the new databases files, you can download and copy the up to date ones (https://github.com/Cpasjuste/pemu/tree/master/pfbneo/data/common/romfs) to the data folder, it should work correctly.

**Comment by RinMaru** [comment]
how do you make a custom gamelist so only the roms that are detected show up? also i use some genesis mods so id like those to show

**Comment by Cpasjuste** [comment]
> how do you make a custom gamelist so only the roms that are detected show up? also i use some genesis mods so id like those to show pgens 6.1 seems to crash when games get added on psvita

I think the option menu "SHOW > AVAILABLE" is what you want.
For the vita problem I'll take a closer look asap.

**Comment by FlawFinder1** [comment]
Yes, for Rin's questions on the PSNES on switch you just hit the plus button and change show from "all" to "available". No need to make a custom list for that. And with the latest update and changing everything in my old list over to the new format for gamelists my custom list is working again. Thank you for fixing this

**Comment by RinMaru** [comment]
> > how do you make a custom gamelist so only the roms that are detected show up? also i use some genesis mods so id like those to show pgens 6.1 seems to crash when games get added on psvita
> 
> I think the option menu "SHOW > AVAILABLE" is what you want. For the vita problem I'll take a closer look asap.

should i make a new issue with the dump attached?

**Comment by Cpasjuste** [comment]
> > > how do you make a custom gamelist so only the roms that are detected show up? also i use some genesis mods so id like those to show pgens 6.1 seems to crash when games get added on psvita
> > 
> > 
> > I think the option menu "SHOW > AVAILABLE" is what you want. For the vita problem I'll take a closer look asap.
> 
> should i make a new issue with the dump attached?

No need thanks, it should be fixed in next release (I hope tomorrow).
