### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#144]
The sound of every SNES game jerks and cracks.
I´ve installed the latest version 5.2 on my PS4 Pro and also on a normal PS4. 
I have this issue on both consoles.
You can hear the issue on [this link](https://sndup.net/gmvm/).

**Comment by Vecinagamer** [comment]
It also happens to me on my ps4 pro.

**Comment by angomania** [comment]
I can confirm that there are no more sound issues with version 6.0
