### ISSUE TITLE
Pgen icon is icon Pnes on Switch

### ISSUE THREAD

**Issue by deejay87** [Cpasjuste/pemu#146]
Hi, not an issue just the icon of Pgen is the icon of Pnes on Switch

**Comment by Vecinagamer** [comment]
yes icono error

**Comment by coestergaard** [comment]
Yes, this is the same problem with both PS4, Nintendo Switch and PSVita versions.

**Comment by Vecinagamer** [comment]
yes

**Comment by Cpasjuste** [comment]
Hi,

Thanks for the report, will fix this asap !
