### ISSUE TITLE
PSVita: pfbneo 6.0 can't show anyrom in list

### ISSUE THREAD

**Issue by box1694** [Cpasjuste/pemu#147]
no rom in gamelist 
back to 5.2 is ok

**Comment by Vecinagamer** [comment]
no rom in gamelist
back to 4.4 the best version is ok

**Comment by coestergaard** [comment]
I see the same. The list of games is empty after I stepped up from 5.2 to 6.0 on my PSVita and PSTV. This happens regardless whether the filter is setup to show all or available roms. It happens for all 4 emulators.
This works perfectly for my Nintendo Switch and PS4 both running version 6.0 as well.

**Comment by Vecinagamer** [comment]
La lista de juegos está vacía después de pasar de 5.2 a 6.0 en mi PSVita. Esto sucede independientemente de si el filtro está configurado para mostrar todas las roms o las disponibles. Sucede para los 4 emus

**Comment by Vecinagamer** [comment]
yes

**Comment by Cpasjuste** [comment]
Thanks for the reports, will fix that today.

**Comment by Cpasjuste** [comment]
Hi guys,

I did found the problem, you need to delete all the "gamelist*.xml" files from the `ux0:/data/pfba/` folder (and preferably the "skins" folder too).

The gamelists files format changed in this version, and they are now embedded in the vpk. If they are found in the `ux0:/data/pfba/` folder then they override the ones in the vpk, which is not good in our case as they are in the old format.
