### ISSUE TITLE
Pfbneo windows error

### ISSUE THREAD

**Issue by hotker79** [Cpasjuste/pemu#149]
libcrypto-1_1-x64.dll was not found reinstalling the program

**Comment by Vecinagamer** [comment]
error also in windows

**Comment by jakenastysnake88** [comment]
Same error here. Tried installing newest MS Visual C++ Redistributable, but no dice.

**Comment by angomania** [comment]
Same error. Also on windows PNES.
I´ve downloaded missing dll from [here](https://de.dll-files.com/libcrypto-1_1-x64.dll.html) (Version. 1.1.1.4. Other versions doesnt work!)
Windows PSNES still crashing after adding dll and roms/screens/video loading. 

Error: 
RomList::build(): ROM_PATH_0: d:\pEMU\test\psnes/roms/ terminate called after throwing an instance of 'std::out_of_range'   what():  stol

PNES is running fine after adding missing dll, roms/screens/videos.

**Comment by Cpasjuste** [comment]
Will be fixed in next release, see https://github.com/Cpasjuste/pemu/issues/153
Thanks for the report.

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
