### ISSUE TITLE
pFBA - Button combinations to enable a "Service and also a "Test" button.

### ISSUE THREAD

**Issue by Winklepicker** [Cpasjuste/pemu#15]
For certain arcade games we need both a "Service and a "Test" button.

Some arcade games currently are fine to adjust, we can change with pfba service button combination and change settings just fine, but it does not work for all arcade games.

e.g "Shinobi" we cant lower the difficulty without both a "Test" and also a "service" button.
Its the same with "Shadow Dancer" and maybe some other Sega arcade games.

Also is their a way to stop many games default to "hard" difficulty?

kinds regards

**Comment by Cpasjuste** [comment]
Hi,

sorry this is not planned!
