### ISSUE TITLE
Pgen psvita

### ISSUE THREAD

**Issue by Vecinagamer** [Cpasjuste/pemu#150]
Pgen in psvita the games are seen with stripes and the screen is not centered like pnes, pnes, games are seen with horizontal stripes

**Comment by Cpasjuste** [comment]
Hi,

Thanks for the report. I just fixed that in latest commit, will try to do a release this weekend.

**Comment by Vecinagamer** [comment]
Ok perfect emulator,,,yeahhh @Cpasjuste ,,,yessssssssssssssss
