### ISSUE TITLE
PS4, PSNES crashes

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#151]
The program psnes crashes on some games if you use L1 + R1 to open the ingame menu and try to quit the game.
PS4 Error CE-34878-0.
For example affected games: Donkey Kong Country, Fifa 97 (Tested only 10 games, those two crashes)

![1](https://user-images.githubusercontent.com/16779776/167088607-162408a8-ce68-40de-8423-7f66a73f1d4c.jpg)
![2](https://user-images.githubusercontent.com/16779776/167088616-467905f5-c34f-455a-9d85-7967bce829d8.jpg)
![3](https://user-images.githubusercontent.com/16779776/167088617-2f021cf9-9c25-4e90-828a-992497752c41.jpg)

**Comment by Vecinagamer** [comment]
It also happens to me on ps4

**Comment by brandon-dodds** [comment]
Happens to me on Switch with Super Mario RPG

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
