### ISSUE TITLE
list games.xm y skin

### ISSUE THREAD

**Issue by Vecinagamer** [Cpasjuste/pemu#152]
If I delete all the lists of game list .xm I get the empty menu and I have the folder with all the roms,,, and what does it have to do with deleting the skin folder if it is only a skin,, if you delete the skin folders, nothing comes out skin, how does that affect, I really don't understand having to delete files gets worse.

**Comment by Cpasjuste** [comment]
No I don't, but if you really want you can via PayPal : https://www.paypal.com/paypalme/cpasjuste

Thanks for the bugs report.

**Comment by Vecinagamer** [comment]
delete all the "gamelist" xml files from the emulators data folders (and also delete the "skins" folder),,this results in an empty game menu,,i just deleted it and nothing appears in the friend menu ,,,if you stop gamelist.xml it does not have a list of games,,wherever it is,,and the same skin,,do it yourself and you will see

**Comment by Cpasjuste** [comment]
Yes I tried it before giving my answer. 
Can you try to rename "pfba" folder to something else, and run the emulator ? It should recreate the "pfba" folder and you should see all games in red. 
Maybe your "config.cfg" is corrupted somehow.

**Comment by Vecinagamer** [comment]
It is not damaged,,, if I delete the gamalist .xml list, there is no list in the menu, regardless of the emulator,, I suggest leaving it as it was as long as it worked very well with the xml lists of a lifetime...
There is also an error in gamegear,, it does not execute the gamegear list,,, mastersystem, megadrive if it executes them well

**Comment by Cpasjuste** [comment]
If there is no list when you delete the XML files in then you are not using pfbneo 6.x I think. Please delete/move "ux0:/data/pfba" folder, delete app from home menu and reinstall vpk.
