### ISSUE TITLE
Missing libcrypto-1_1-x64.dll, Windows PSNES, PNES, PFBNEO, PGEN

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#153]
All windows PEMU versions doesnt start. Error: libcrypto-1_1-x64.dll is missing.
I´ve downloaded missing dll from [here](https://de.dll-files.com/libcrypto-1_1-x64.dll.html) (Version. 1.1.1.4. Other versions doesnt work!)

Windows PSNES is crashing after adding dll and roms/screens/video.

Error:
RomList::build(): ROM_PATH_0: d:\pEMU\test\psnes/roms/ terminate called after throwing an instance of 'std::out_of_range' what(): stol

PNES and PGEN are running fine after adding missing dll and roms/screens/videos.

Didnt tested pfbneo yet.

**Comment by Cpasjuste** [comment]
Thanks for the report. 
For the missing dll, it's solved and will be ok in next build.
For psnes I'll take a look asap.

**Comment by angomania** [comment]
PFBNEO also crashes after adding dll and roms/screens/video.

Error:
RomList: building list...
RomList()
terminate called after throwing an instance of 'std::out_of_range'
  what():  stol

**Comment by Cpasjuste** [comment]
You can try this dll: <https://github.com/Cpasjuste/pemu/blob/master/data/windows/datadir/libcrypto-1_1-x64.dll?raw=true>
I don't think it's related but well.

**Comment by angomania** [comment]
Tried this Dll already. Problem with pFbneo & pSnes still exists.

pSnes & pFbneo is starting normal without roms. 
If I added roms pSnes & pFbneo are crashing.

I use the recommended romsets for both.

**Comment by Cpasjuste** [comment]
Thanks for the testing, will fix that asap.

**Comment by Cpasjuste** [comment]
Hi @angomania,

You could test the attached file (psnes executable), i think i fixed the bug. An new release will be available tomorrow (i hope).
[psnes.zip](https://github.com/Cpasjuste/pemu/files/8644489/psnes.zip)

**Comment by angomania** [comment]
I've been a big fan of emulators for many years.
I admire your work. Creating PEMU for so many different platforms is a big challenge.

I like PEMEU. The screens and videos are also great. thanks for your work

**Comment by angomania** [comment]
> Hi @angomania,
> 
> You could test the attached file (psnes executable), i think i fixed the bug. An new release will be available tomorrow (i hope). [psnes.zip](https://github.com/Cpasjuste/pemu/files/8644489/psnes.zip)

Ist working now with all roms/snaps/videos. Good job! :)

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
