### ISSUE TITLE
pGEN crashes at start on PS4  

### ISSUE THREAD

**Issue by Ariastar** [Cpasjuste/pemu#154]
pGEN crashes at start on PS4  . Error CE-34878-0

**Comment by Vecinagamer** [comment]
yes error ps4

**Comment by Cpasjuste** [comment]
Thanks for the reports, should be fixed for next release, see https://github.com/Cpasjuste/pemu/issues/128 and https://github.com/Cpasjuste/pemu/issues/153

**Comment by NanospeedGamerYT** [comment]
Verifico que no funciona en ps4

**Comment by Cpasjuste** [comment]
> Verifico que no funciona en ps4

Yeah you need to wait for the next release to verify this ! :)

**Comment by NanospeedGamerYT** [comment]
Sure! I'm just verifying the comment of the previous user, that the Version available for ps4 does not work! Cheers
I'm waiting for the next version

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
