### ISSUE TITLE
Pgen

### ISSUE THREAD

**Issue by ReysNelly** [Cpasjuste/pemu#155]
pGen trava ao iniciar

**Comment by Cpasjuste** [comment]
Hi, on which device ? PS4, vita, switch..? Thanks.

**Comment by Vecinagamer** [comment]
Yo in ps4 broken

**Comment by ReysNelly** [comment]
Ps4 Slim

**Comment by Cpasjuste** [comment]
Thanks for the reports, should be fixed for next release, see https://github.com/Cpasjuste/pemu/issues/128 and https://github.com/Cpasjuste/pemu/issues/153

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
