### ISSUE TITLE
Vita PFBNeo 6.1 cannot handle large rom set

### ISSUE THREAD

**Issue by coestergaard** [Cpasjuste/pemu#156]
I have what I believe is a complete set of ROMS forr PFBNeo.
The set works perfectly with PFBNeo 6.1 on both my Nintendo Switch and my PS4.
It also used to work fine with PFBNeo 5.2 on my PS Vita.
However since I updated to PFBNeo 6.0/6.1 it crashes during startup. If I only place a few ROM files in the rom folder it works fine, but if I place some thousands of files it crashes. That was not the case with version 5.2. I have tried to uninstall the program and delete the pfba folder and reinstalled it again but it still fails.
And by the way thanks for your fantastic work! I really appreciate it!

**Comment by robpinheiro** [comment]
i think this is the same problem than i reported here
https://github.com/Cpasjuste/pemu/issues/128

**Comment by box1694** [comment]
is the same problem

**Comment by Vecinagamer** [comment]
Yes is my problem psvita

**Comment by Cpasjuste** [comment]
Thanks for the reports, should be fixed for next release, see https://github.com/Cpasjuste/pemu/issues/128 and https://github.com/Cpasjuste/pemu/issues/153

**Comment by Vecinagamer** [comment]
Filter Advance-aa,,,it looks quite bad and blurry,,,I would change it or put another one that looks better.

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
