### ISSUE TITLE
Roms PGEN

### ISSUE THREAD

**Issue by NanospeedGamerYT** [Cpasjuste/pemu#158]
Hello! where do the pgen roms go?
I have tried several options and I do not see any rom logo
Thank you

**Comment by Cpasjuste** [comment]
Hi,

It's explained here: https://github.com/Cpasjuste/pemu/tree/master/pgen

**Comment by NanospeedGamerYT** [comment]
I tell you my experience with PSVITA, I have added PReviews + Megadrive Roms, I have tried the emulator and everything is perfect
But there is a problem, if I add any ROM from gamegear or master System, the console crashes... it doesn't start the application

**Comment by Cpasjuste** [comment]
Yep, I think the problem is like another reports, there is now a crc check on files to recognize them and it seems I didn't properly handle that. It should be fixed in next version (tomorrow I hope).

**Comment by Vecinagamer** [comment]
Thanks 😉
