### ISSUE TITLE
The Option Button and the Touch Button do not work on PS4. neither on PBNeo nor PSNES. And PGEN crashes

### ISSUE THREAD

**Issue by snake1978** [Cpasjuste/pemu#159]

**Comment by snake1978** [comment]
The Option Button and the Touch Button do not work on PS4. neither on PBNeo nor PSNES. And PGEN crashes

**Comment by FlawFinder1** [comment]
To open the options button on PSNES when inside a game hitting the - and the + at the same time works for me. If I'm in the game selection just the +. I have noticed however that the button to favorite things is X when the instructions on the bottom say to press Y. And the joycon deadzone preset seems around 190 too low. Not sure what you mean by touch button and I've never tried any of the emulators other than PSNES

**Comment by Vecinagamer** [comment]
Yes error opción

**Comment by Cpasjuste** [comment]
Hi, here it seems to works fine (v6.4), i can use them and remap them. Can you be more specific on the problem ?

**Comment by Cpasjuste** [comment]
Closing since no answer.
