### ISSUE TITLE
Psnes 3.4 do not show the preview

### ISSUE THREAD

**Issue by m0ckeyl0ck** [Cpasjuste/pemu#16]
the psnes dont show the previews just only y press the R or L, before releases do it alone, any help??

**Comment by azoreseuropa** [comment]
> the psnes dont show the previews just only y press the R or L, before releases do it alone, any help??

It works for me. Make sure you rename preview.png to match rom's name. For an example: Zelda.png Zelda.rom

**Comment by m0ckeyl0ck** [comment]
Yes i know but what i said, i have to press R to see the gama preview, can you see the preview anytime you scroll games or you have to press R or L to activate the preview

**Comment by azoreseuropa** [comment]
When I scroll down to select the rom and I just press R to activate the preview. Worked for me. Yes, I am using the latest version.

**Comment by m0ckeyl0ck** [comment]
That’s what i said in before releases you don't have to press R or L the preview shows up automatically

**Comment by azoreseuropa** [comment]
No, I can only see title when I scroll games but if you want to see the preview then you have to press R to see the preview. Press R again to see the title.

**Comment by rsn8887** [comment]
You can also just move your shots from the preview to the title folder.

**Comment by beven** [comment]
The problem appears to be fixed if you put the images in the "titles" folder. Not sure if there is intentional but it is a work around at the moment.
