### ISSUE TITLE
[Switch] Single joycons handling not working

### ISSUE THREAD

**Issue by R-YaTian** [Cpasjuste/pemu#160]
I build pfbneo [c62f785](https://github.com/Cpasjuste/pemu/commit/c62f7858ebd8b2a7fe25b9549b4f55ac058bf601) myself, and single joycons mode not working...

**Comment by Cpasjuste** [comment]
Hi,

I'm waiting the "go" from the devkitpro maintener to merge latest changes : https://github.com/devkitPro/SDL/tree/switch-sdl2-2.0.14-dev

**Comment by R-YaTian** [comment]
> 

Hello!
Thanks for you quick reply. I try to rebuild it with "SDL2_2.0.14-dev". But I got this error:
"skipping incompatible /opt/devkitpro/portlibs/switch/lib/libSDL2.a when searching for -lSDL2"

**Comment by Cpasjuste** [comment]
Are you using configure scripts? If so then I may have to fix that. Locally I'm using cmake to build it, so the cmake way should work for you

**Comment by R-YaTian** [comment]
> Are you using configure scripts? If so then I may have to fix that. Locally I'm using cmake to build it, so the cmake way should work for you

Maybe I should use cmake with "-DNINTENDO_SWITCH=ON", idk...hmmm

**Comment by Cpasjuste** [comment]
This flag should be automatically set when you use the switch cmake toolchain file (-DCMAKE_TOOLCHAIN_FILE=...) (Sorry I'm on phone it's hard to fully help :) )

**Comment by R-YaTian** [comment]
> This flag should be automatically set when you use the switch cmake toolchain file (-DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/...) (Sorry I'm on phone it's hard to fully help :) )
> 
> Also, single joycons is handled here now if you have some suggested changes: https://github.com/devkitPro/SDL/blob/switch-sdl2-2.0.14-dev/src/joystick/switch/SDL_sysjoystick.c

OK. I succeed in building "SDL2_2.0.14-dev". Thanks for your help! I will test new sdl single joycons later on.

**Comment by R-YaTian** [comment]
> This flag should be automatically set when you use the switch cmake toolchain file (-DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/...) (Sorry I'm on phone it's hard to fully help :) )
> 
> Also, single joycons is handled here now if you have some suggested changes: https://github.com/devkitPro/SDL/blob/switch-sdl2-2.0.14-dev/src/joystick/switch/SDL_sysjoystick.c

Single joycons mode works fine now, but I think we should set NpadJoyHoldType_Horizontal for it. I opened [a new PR](https://github.com/devkitPro/SDL/pull/16) for that.
