### ISSUE TITLE
pEMU 6.0 Windows, Sound Issues

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#163]
All Windows emus (pNes, pSnes, pGen, pFba) have sound issues.  
Like the same issues I described for the PS4. (Speed, dropouts, cracking)

**Comment by Cpasjuste** [comment]
"Cool", thanks for the report once again. I couldn't really test the windows port (my main computer is linux), will debug this asap.

**Comment by Cpasjuste** [comment]
Hi @angomania,

Should be fixed in next release (you can test it with the attached file)
[psnes.zip](https://github.com/Cpasjuste/pemu/files/8646582/psnes.zip)
.

**Comment by angomania** [comment]
> 

I tested it, the sound is ok now. :)

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
