### ISSUE TITLE
pEmu 6.0 Windows pSnes, crash after opening ingame menu

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#164]
I´ve noticed crashes on some games if you try to open the ingame menu. (Same crash like on the PS4)
For example at "Doom Troopers - Mutant Chronicles (USA)" and all "Donkey Kong Country 1" roms. 

There are too many roms to test them all ;)

**Comment by Cpasjuste** [comment]
Yeah thanks, this is enough for me to debug!

**Comment by AlbertoDiazC** [comment]
I can't play DKC1 on switch too, sometimes doesn't load at all, other times freezes when opening the in game menu. Perhaps it happens only with large size roms.

**Comment by Cpasjuste** [comment]
Found the problem, some games needs different audio buffer size, and I'm not handling that (memory corruption). Will be fixed for next release :)

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2). If not, be sure to report here and i'll re-open the issue.
