### ISSUE TITLE
psnes: Elfaria game missing from nointro database

### ISSUE THREAD

**Issue by AlbertoDiazC** [Cpasjuste/pemu#165]
The latest psnes gamelist.xml has dropped
Elfaria - The Isle of the Blest (Japan).zip
which is part of the 2017-05-29 nointro romset. Old psnes versions did have support for it. Maybe some script has inadvertedly filtered it.

**Comment by Cpasjuste** [comment]
Hi,

Thanks for the report. Yes i'm not sure what happened, i added it manually and will be available in next release (minus medias).

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in [6.3](https://github.com/Cpasjuste/pemu/releases/tag/v6.3) (currently uploading), if not be sure to report here so i re-open the issue.
