### ISSUE TITLE
unable to to run pgen-6.0 on Windows 7, ScriptFreeCache could not be located

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#166]
I am unable to to run pgen-6.0 for Windows. I got this error message:
"The procedure entry point ScriptFreeCache could not be located in the dynamic 
link library GDI32.dll".
Windows is Windows 7 x64 SP2
I have found some info regarding this issue on web, dunno if this applies:
https://docs.microsoft.com/en-us/windows/win32/api/usp10/nf-usp10-scriptfreecache

**Comment by Cpasjuste** [comment]
Hi @MayanKoyote,

I'm sorry but i won't find the time (nor motivation) to support windows 7 (unless someone take over it).
