### ISSUE TITLE
PSVita - cannot use custom rom path (like the path from retroarch) in any of the emulators

### ISSUE THREAD

**Issue by theshinyknight** [Cpasjuste/pemu#167]
I have modified the config file so I can use both the internal path (data/EMULATOR/SYSTEMNAME) and one of my choice, but it seems that all the emulators (Pnes, Psnes, Pfba) always use the default one (which is the one in the data folder).

This result in all the playlist to be empty, unless all the roms are in the default folder. I looked in the code and saw the assign for the default path, but I am not sure where the assign is done reading the config file, because it seems that it is not executed.

I can reproduce by simply changing the path in the config file to something like UX0:/roms/SYSTEMNAME in the ROMS_PATHS array. But it does not use that path, either if I replace the first entry of the array (ROMS_PATH0) or if I append a new path at the end of the array (ROMS_PATH15).

**Comment by Cpasjuste** [comment]
Hi,

Multiple roms path is not currently supported or planned, sorry. "ROMS_PATHXX" are only here for pfbneo as it needs multiple roms paths for each system.

**Comment by theshinyknight** [comment]
So you can only have one path per system even for pfbneo?
The problem that even changing that one single path does not work. The only path working is the one you hardcoded as default
