### ISSUE TITLE
PGEN Vita Softlock

### ISSUE THREAD

**Issue by RinMaru** [Cpasjuste/pemu#168]
v6.2 Vita
so the app doesnt crash but its locking when scanning for games. theres no log either so i cant really pin where it starts

**Comment by Vecinagamer** [comment]
Broken pgen psvita

**Comment by RinMaru** [comment]
broken on windows too

**Comment by robpinheiro** [comment]
the same with psnes

**Comment by RinMaru** [comment]
> the same with psnes

im guessing its getting overloaded with roms its scanning.

**Comment by robpinheiro** [comment]
I performed some tests and 252 roms takes 1min and 43sec to open psnes.
It's strange because in version 5.2 it was instant

**Comment by Cpasjuste** [comment]
Hi,

The "problem'" is you are probably not using the recommended romset (as seen [here](https://github.com/Cpasjuste/pemu/tree/master/pgen)). 
Still, will change the way unknown roms are loaded (remove the crc calculation of them for id)

**Comment by Cpasjuste** [comment]
Hi @robpinheiro, could you try with the attached "psnes.vpk" (unzip to get vpk)
[psnes.zip](https://github.com/Cpasjuste/pemu/files/8649560/psnes.zip)
?

**Comment by robpinheiro** [comment]
@Cpasjuste this worked perfectly lol.
The only thing that doesn't work is the function to add games that are not present in the gamelist.xml to favorites, as reported in this topic https://github.com/Cpasjuste/pemu/issues/129
