### ISSUE TITLE
Change background doesn't worked for pSNES - help ?

### ISSUE THREAD

**Issue by azoreseuropa** [Cpasjuste/pemu#17]
The problem is: 

I want to replace my background. I rename it in config in skin folder like this:

> MAIN :
> {
> texture = "skins/title.png"

 to match my correct resolution size and its in .png which is bg.png

And test it. No changed at all. am confused. HELP?!

**Comment by azoreseuropa** [comment]
Hello?

**Comment by azoreseuropa** [comment]
Never mind. Someone helped me out at GBATEMP private message. Everything's fine now. Thanks anyway.

**Comment by killsting** [comment]
> Never mind. Someone helped me out at GBATEMP private message. Everything's fine now. Thanks anyway.

Can you teach me how to replace the bg?

**Comment by azoreseuropa** [comment]
> > Never mind. Someone helped me out at GBATEMP private message. Everything's fine now. Thanks anyway.
> 
> Can you teach me how to replace the bg?

Go to gbatemp and contact Bisk8 who helped me out. I haven't used it for a while so I don't have time to check it again but maybe other time. If you don't want to wait then contact Bisk8 at gbatemp. He will be happy to give you an answer you are seeking. :)
