### ISSUE TITLE
(Feature request) / BUG PGEN User Defined Bios

### ISSUE THREAD

**Issue by RinMaru** [Cpasjuste/pemu#170]
seems bios files don't work unless directly selected in a roms folder rather than in bios folder. would be nice if we could define what's bios we use just to avoid the trouble of looking for the conventional names RA has ppl use.

**Comment by Cpasjuste** [comment]
Hi @RinMaru ,

I'm not sure to understand what you mean, are you saying that bios files (as described here: https://github.com/Cpasjuste/pemu/tree/master/pgen) does not gets loaded when put in the "pgen/bios" folder? Here it seems to works fine. Genesis Plus GX automatically select the needed bios to load (it's why names are hardcoded).

**Comment by Cpasjuste** [comment]
> > Hi @RinMaru ,
> > I'm not sure to understand what you mean, are you saying that bios files (as described here: https://github.com/Cpasjuste/pemu/tree/master/pgen) does not gets loaded when put in the "pgen/bios" folder? Here it seems to works fine. Genesis Plus GX automatically select the needed bios to load (it's why names are hardcoded).
> 
> yea i had my bios named correctly but sega cd failed to load. not sure if its due to the sega cd games being in chd format or the fact i have the Sega CDX bios

Yes probably because chd support was not added, it should now work with 6.3.
