### ISSUE TITLE
PGEN 7z and CHD files unreadable

### ISSUE THREAD

**Issue by RinMaru** [Cpasjuste/pemu#171]
7z Megadrive and gamegear roms aren't recognized and while Sega CD CHD games show up in ALL filter, none will play. is this a bug or a dependency not yet covered?

**Comment by Cpasjuste** [comment]
Hi @RinMaru,

7z support is not natively supported in Genesis Plux GX and so won't be supported soon in pgen.
For CHD games, i need to implement that, will do that asap.

**Comment by Cpasjuste** [comment]
Hi,

CHD support was added in latest code, will be available in next release.

**Comment by RinMaru** [comment]
> Pgen 6.3 roms mega cd,,doesn't load them,,I have them in their folders just like megadrive works,,,master-system works,,game gear works,,,mega-cd doesn't work

do you have bios_CD_U.bin in the bios folder?

**Comment by tanaduda** [comment]
> Pgen 6.3 roms mega cd,,doesn't load them,,I have them in their folders just like megadrive works,,,master-system works,,game gear works,,,mega-cd doesn't work

PGEN doesnt crash for you while opening?

**Comment by Cpasjuste** [comment]
Hi,

For me the problem is solved (except 7z support Wich is not planned yet), closing the issue!

**Comment by eiflax** [comment]
just tried now current actual version on ps4. Sega Mega CD chd files are not detected. Am I missing some extra detail ?
