### ISSUE TITLE
pGEN 6.3 on PS4 crash at launch with error CE-34878-0

### ISSUE THREAD

**Issue by matcarfer** [Cpasjuste/pemu#172]
pGEN 6.2 on PS4 crash at launch with error CE-34878-0
All other 3 emus load fine.
EDIT: Also tested 6.3, it crashes too.

**Comment by Vecinagamer** [comment]
Ce-34878-0 error ps4 pgen 6.2

**Comment by angomania** [comment]
On my PS4 Pro too. Ps4 crashes after boot screen. Error CE-34870-0
The required folders and "config.cfg" are created in the \data directory. (Maybe this info will help)

**Comment by matcarfer** [comment]
6.3 still crashes

**Comment by angomania** [comment]
Same here. Still crashes on 6.3

**Comment by Cpasjuste** [comment]
Hi, this is fixed in next release (will be released this week).

**Comment by matcarfer** [comment]
can confirm 6.5 fixed this issue.
