### ISSUE TITLE
pGen crash ps4

### ISSUE THREAD

**Issue by Ariastar** [Cpasjuste/pemu#174]
pGen still crashes on start on ps4. (pGen 6.2)

**Comment by angomania** [comment]
On my PS4 Pro too. Ps4 crashes after boot screen. Error CE-34870-0
The required dolders and "config.cfg" are created in the \data directory. (Maybe this info will help)

**Comment by Cpasjuste** [comment]
Duplicate, see https://github.com/Cpasjuste/pemu/issues/172
