### ISSUE TITLE
pEmu (pNes,pSnes,pFbneo) PS4, info bar is showing wrong key assignment

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#175]
Small cosmetic flaw.
The info bar shows the wrong key assignment for: "Add/Remove Favorite", "Rom Menu" and "Main Menu".
On my PS4 the key "Add/Remove Favorite" is SQUARE, "Rom Menu" is LEFT SHOULDER and "Main Menu" is RIGHT SHOULDER.

The key assignment (pFbneo) "Switch System" it´s ok.
![11111_Leiste](https://user-images.githubusercontent.com/16779776/167362083-cfc28266-d960-4042-9e96-1fdf67a22037.jpg)

**Comment by tanaduda** [comment]
Assigned Y and B button are inverted with X and A too (snes default).

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in [common: fix wrong keys assignment in help bar (hopefully)](https://github.com/Cpasjuste/pemu/commit/0a1e0f357b739bf736e877cdd69ca64e56072652).

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (currently building/uploading), will reopen the issue if it's not the case.
