### ISSUE TITLE
Game gear pgen v6.2 psvita

### ISSUE THREAD

**Issue by Vecinagamer** [Cpasjuste/pemu#177]
Hello, everyone.
First of all my thanks to @cpasjuste for the hard work that Pemu is giving him, thanks friend.
Problem with game gear, the screen is not centered in full.
The image is reproduced in the left corner,,,instead of being centered

**Comment by Cpasjuste** [comment]
Hi, thanks for the report. This is fixed and will be available in next release.

**Comment by Vecinagamer** [comment]
Thanks

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in [6.3](https://github.com/Cpasjuste/pemu/releases/tag/v6.3), if not be sure to report here so i re-open the issue.

@Vecinagamer, be sure to put all the required bios in bios folder has described here: https://github.com/Cpasjuste/pemu/tree/master/pgen
