### ISSUE TITLE
vita: wrong help buttons

### ISSUE THREAD

**Issue by Cpasjuste** [Cpasjuste/pemu#178]
button to add to favorites is showing that it is the triangle but the correct one is square (https://github.com/Cpasjuste/pemu/issues/168#issuecomment-1120968102)

**Comment by Vecinagamer** [comment]
yeahhhh

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in [common: fix wrong keys assignment in help bar (hopefully)](https://github.com/Cpasjuste/pemu/commit/0a1e0f357b739bf736e877cdd69ca64e56072652).

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (currently building/uploading), will reopen the issue if it's not the case.

**Comment by Vecinagamer** [comment]
Thanks
