### ISSUE TITLE
pGEN

### ISSUE THREAD

**Issue by ReysNelly** [Cpasjuste/pemu#180]
pGEN no PS4 erro CE-3487-0

**Comment by Vecinagamer** [comment]
Pgen 6.3 roms mega cd,,doesn't load them,,I have them in their folders just like megadrive works,,,master-system works,,game gear works,,,mega-cd doesn't work

**Comment by joesayegh** [comment]
I don't believe this but pGEN still doesn't work on PS4. (CE-34878-0)
I'm using the latest version, 6.3 at the time of writing this.

**Comment by Vecinagamer** [comment]
I can check and see    @Cpasjuste

**Comment by joesayegh** [comment]
Hi @Cpasjuste, apologies for sounding ungrateful. You've built something AMAZING here!
I've placed the bios files (areplay.bin, bios.gg, bios_CD_E.bin etc.) in the bios directory.
I've updated the rom paths in config.cfg. When the emulator starts, the rom scan initialises.
It gets to 1356 /1914, then it crashes, and I get the CE-34878-0 error.
I just can't seem to get it to work.

**Comment by Vecinagamer** [comment]
@Cpasjuste   You've built something AMAZING here!,,,YES ,,YES YESSS

**Comment by Cpasjuste** [comment]
Duplicate, closed in favor of https://github.com/Cpasjuste/pemu/issues/172
