### ISSUE TITLE
pGen 6.3 Windows, Mega CD games not loading

### ISSUE THREAD

**Issue by angomania** [Cpasjuste/pemu#182]
Error: Invalid File
Romset: "[REDUMP] Disc Image Collection Sega - Sega Mega CD updated 2021-01-08 (20-42-03)"

![11111](https://user-images.githubusercontent.com/16779776/167553716-0bef5614-7506-4160-ae77-dcfb3fe0d589.jpg)
![111112](https://user-images.githubusercontent.com/16779776/167553742-4d8f07d6-34a0-4956-bccc-e0cdc8e35689.jpg)

**Comment by Vecinagamer** [comment]
Games chd yes loading

**Comment by Cpasjuste** [comment]
Hi @angomania ,

I'm unable to reproduce your problem on windows 10 with pgen 6.3. Be sure to put all the required bios in the "bios" folder (see [readme](https://github.com/Cpasjuste/pemu/tree/master/pgen)).

If all seems good on your side then i'll reopen the issue.

**Comment by RinMaru** [comment]
> Error: Invalid File
> Romset: "[REDUMP] Disc Image Collection Sega - Sega Mega CD updated 2021-01-08 (20-42-03)"
> 
> ![11111](https://user-images.githubusercontent.com/16779776/167553716-0bef5614-7506-4160-ae77-dcfb3fe0d589.jpg)
> ![111112](https://user-images.githubusercontent.com/16779776/167553742-4d8f07d6-34a0-4956-bccc-e0cdc8e35689.jpg)
> 
> 

You need allsega cd bios files named as BIOS_CD_U.bin 
BIOS_CD_E.bin BIOS_CD_J.bin

**Comment by angomania** [comment]
My fault. Its working.
Forgot to copy the bios files :)
