### ISSUE TITLE
pGen Game-specific save file for Sega CD

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#184]
I noticed that for saves, the pGen can create Sega/Mega CD RAM Cart file scd_bram_cart.brm and per bios Sega/Mega CD US/EU/JP Backup RAM file scd_bram_u/e/j.brm.
Is it possible to have option to ask the core to make one Sega/Mega CD Backup RAM file per game instead?
Ability to select save per bios / per game option in the settings?
Example: You save in a game that has the file name "Snatcher (USA).cue". The game would save to the file "Snatcher (USA).brm".
As far as I understand, there is such a possibility in the libretro:
https://github.com/ekeeke/Genesis-Plus-GX/issues/100
https://docs.libretro.com/library/genesis_plus_gx/

**Comment by Cpasjuste** [comment]
Hi,

Should I implement that for both save files ? 
Also, what about doing this by default, do you see any drawback ? (Would simplify the code a little).

**Comment by MayanKoyote** [comment]
Hello.
I think this should only apply to the Sega/Mega CD Backup RAM file, the one that is small in size. It will be more practical in terms of taking up space.
And about setting it by default - I think it would be logical. By name of the file it will be clear that this file contains records from this particular game. This file can then be safely copied for backup or exchange.

**Comment by Cpasjuste** [comment]
This is done ([pgen: save per game mega-cd backup ram](https://github.com/Cpasjuste/pemu/commit/30dcbd52ee75b2b5977bffdc892b55fcd96bbcf0)) and will be available in next release, thanks for the idea.

**Comment by MayanKoyote** [comment]
Thank you very much.
So far I'm checking, but looks like it's something similar to:
https://github.com/Cpasjuste/pemu/issues/186#issuecomment-1124046331
I'll say more precisely a bit later, checks take time.

**Comment by MayanKoyote** [comment]
> Thank you very much. So far I'm checking, but looks like it's something similar to: [#186 (comment)](https://github.com/Cpasjuste/pemu/issues/186#issuecomment-1124046331) I'll say more precisely a bit later, checks take time.
> 
> Found a game for a quick checks, Rise of the Dragon. Yes, it turned out to be what I suspected. Cartridge RAM file - scd_bram_cart.brm - is created, written and read successfully. And the Sega CD internal RAM memory file - nameofgame.brm - is created and written successfully, but the game cannot see (and read) an already existing file.

Looks like that fix:
https://github.com/Cpasjuste/pemu/issues/186#issuecomment-1124613583
also fixed it.
Thank you very much.
