### ISSUE TITLE
pGen v6.3 PSVita Cannot Save State, Crash

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#185]
PS Vita (PCH-1000), FW 3.60, HENkaku Release 11 Ensō v1.1, psvsd
pGen v6.3
Being in the game I open up the menu with Start + Select, go to States, choose a slot, then try to save by pressing X.
At this point, I immediately get a crash with an error:
"An error has occurred in the following application.
(C2-12828-1)
Saved Core File Succeeded.
ux0:data/psp2core-[lot of digits]-eboot.bin.psp2dmp"
Save state is not created, nothing new in the subfolders of ux0:data/pgen/

So far I've tried it on a Sega CD game.
Now I'll check what will happen in the case of SMD and SMS games, will add the result.

**Comment by Cpasjuste** [comment]
Hi, thanks for the report. This is fixed and will be available in next release.

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (currently building/uploading), will reopen the issue if it's not the case.

**Comment by Cpasjuste** [comment]
Oops, Im doing all my development/testing without sound... Yeah a new issue could be cool, but I can do it tomorrow.

**Comment by MayanKoyote** [comment]
It looks like version v6.5 solved the problem with the loss of sound after loading from Save States. Thank you.
