### ISSUE TITLE
pGen v6.3, For SMS and SMD games with built-in save options, save files (*.srm) are not created.

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#186]
_I can only run pGen on PSVita now. Therefore, I do not know if the problem applies to any pGen variant or if it is typical only for PSVita._

There are some games for SMS and SMD that have ability to save progress to sram (backup memory). It's not save state, it's internal in-game feature of game, cartridge RAM.
As far as I understand, this is implemented by creating a *.srm file with the same name as the rom file.

_there is also moment that for each game you don’t need to create such a file, you need some kind of check whether the game needs it or not_
_https://github.com/ekeeke/Genesis-Plus-GX/issues/19_

I checked Phantasy Star (USA, Europe) (Rev 3) SMS game.
When using the in-game Save function, nothing new is created in the subfolders of ux0:data/pgen/.
Accordingly, progress is not saved. And there is no option to continue the game by selecting Continue the next time you start the game.

Also I checked Wonder Boy in Monster World (USA, Europe) SMD game.
_Here, in-game saves are possible in the Inn, this is not immediately at the beginning of the game, you have to go through several screens, but anyway._
When using the in-game Save function, nothing new is created in the subfolders of ux0:data/pgen/.
If to not "reset" the game by completely exiting it through the emulator menu, then the save remains in emulator's memory. And it is possible to continue the game by going to the main game menu screen and selecting Continue.
But if you completely exit the game and start it again, then there will be no Continue option. Which is logical, since there is no where to read the backup memory from (no corresponding  *.srm file).

**Comment by Cpasjuste** [comment]
Hi,

Thanks, it will be available in next release.

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (currently building/uploading), will reopen the issue if it's not the case.

**Comment by MayanKoyote** [comment]
Checked v6.4. Now the required *.srm files are created.
But then something strange begins.
Either the next time you load the game after exiting the game or after closing and restarting the application, the emulator does not find and read this corresponding file, or something else.
In any case, the game behaves as if there is no save. There are no offers to continue the game from the saved moment or the list of saves is empty.
So far, I'm looking at what is written to the files.
SMD Pier Solar's save file looks like filled with the same characters, kinda like empty. But it's a technically weird game by itself.
SMD Ys III's file looks like have save inside. I'll try to put it in another emulator for check.
SMS Phantasy Star's file also looks like have save inside. I'll try to put it in another emulator for check.

**Comment by Cpasjuste** [comment]
Hi,

Don't bother, I think I found the problem (and it's also probably a problem for CD_BRAM_CART). 
The game name is not yet set when I load them... :x So the save filename is wrong and can't be opened.... Will fix that tomorrow.

**Comment by Cpasjuste** [comment]
Hi @MayanKoyote , this is fixed for next release (for sure this time, tested with Ys III).
In the meantime here is a fixed vpk:[pgen.zip](https://github.com/Cpasjuste/pemu/files/8675744/pgen.zip)
