### ISSUE TITLE
pGen v6.3, Size of Sega CD Backup RAM Cart file scd_bram_cart.brm

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#188]
_I can only run pGen on PSVita now. Therefore, I do not know if this applies to any pGen variant or if it is typical only for PSVita._

pGen v6.3 create Sega CD Backup RAM Cart file scd_bram_cart.brm with size of 8256 kB. Why it's so big?
According to this: https://segaretro.org/CD_BackUp_RAM_Cart
maximum size of officially-released RAM cartridge for the Sega CD was 1 Mbit or 128 kB (2045 blocks (2048 - 3 for the filesystem tables)),
and maximum theoretical size is 4 Mbit or 512 kB (8189 blocks (8192 - 3 for the filesystem tables)).
I know that there were 3rd-party RAM cartridges with capacity of 512 kB.
Genesis Plus GX emulates 512kB RAM cart by default:
https://github.com/ekeeke/Genesis-Plus-GX/issues/267

**Comment by Cpasjuste** [comment]
Hi, you're right, thanks for the tips. I just didn't take enough time to look closely as this (lot of work on pemu..).
This is fixed and will be ready for next release.

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [v6.4](https://github.com/Cpasjuste/pemu/releases/tag/v6.4) (currently building/uploading), will reopen the issue if it's not the case.

**Comment by Vecinagamer** [comment]
thanks
