### ISSUE TITLE
Bottons pemu psvita game roms

### ISSUE THREAD

**Issue by Vecinagamer** [Cpasjuste/pemu#190]
Pemu now the games go to 58 fps much better, thank you very much for the great effort to make them work @cpasjuste,,,,
The games,,outrun,super hang-on,chase-hq,,there is no button to accelerate,no brake,,,the stick works fine.

**Comment by Cpasjuste** [comment]
Hi @Vecinagamer ,

I think if you assign L/R triggers to LB/RB in menu it could work.

**Comment by Vecinagamer** [comment]
@Cpasjuste the controls are ok,thanks to much
