### ISSUE TITLE
Pfbn issue with toggling settings

### ISSUE THREAD

**Issue by joelsaacks** [Cpasjuste/pemu#192]
If I press start and select together and switch eg. Show clones. Its changes from off to on to back to on again. Same with show zip names. Not always but often. I had to edit the config file to manually do it. Saw it on version 6.4

**Comment by Cpasjuste** [comment]
Hi, thanks for the report, this was a "major" bug in input handling. This is fixed and will be ready for next release.

**Comment by Vecinagamer** [comment]
Thanks very much

**Comment by joelsaacks** [comment]
Fantastic. This app is getting better and better
