### ISSUE TITLE
FPS counter doesn't work (psnes VITA)

### ISSUE THREAD

**Issue by robpinheiro** [Cpasjuste/pemu#194]
hi thanks for the excellent work. I found a bug in psnes.
When the fps counter is activated it is stuck at 0.0/60.0

**Comment by Manfred282** [comment]
confirmed, on pfbneo (Vita) the fps counter is the same, stuck at 0.0/60 ... not working at all

**Comment by Cpasjuste** [comment]
Hi, thanks for the report, this is fixed for next release.

**Comment by Vecinagamer** [comment]
thanks very much   @Cpasjuste
