### ISSUE TITLE
[Request] A nice XBOX UWP release would be awesome 😃

### ISSUE THREAD

**Issue by 20Phoenix** [Cpasjuste/pemu#196]
Hello :)
I love your pemus and would love to see them working on XBOX One/Series aswell.
So a nice XBOX UWP release would be awesome 😃
Is that possible / doable / already planned / in progress ?

**Comment by Cpasjuste** [comment]
Hi @20Phoenix ,
I'm sorry but this is not planned! (Lack of time and Xbox)
