### ISSUE TITLE
Crashes when enabling „single Joycon“

### ISSUE THREAD

**Issue by rsn8887** [Cpasjuste/pemu#2]
Thanks for the amazing emulators!

One small thing with latest versions 3.0 etc.:
When I turn single joycon to ON in the options, the emulator crashes.

I have working single joycon mode code here. 
https://github.com/rsn8887/uae4all2/blob/655bc18c845998b7c530806ba97ba1dda786dce5/src/gui.cpp#L205

With the above code, `update_joycon_mode()` needs to be called once per frame (because we never know, the user can attach/detach controllers at any time), and `mainMenu_singleJoycons` is a variable that can be set to one or zero in the menu to enable/disable single joycon mode.

**Comment by rsn8887** [comment]
See PR https://github.com/Cpasjuste/libcross2dui/pull/3

Hopefully fixes it (cannot test atm, but anything is better than crash :) ).

**Comment by Cpasjuste** [comment]
Thanks @rsn8887, fixed in latest commits
