### ISSUE TITLE
pnes 3.40: filter / effect not applied from the start

### ISSUE THREAD

**Issue by Tardigrade-nx** [Cpasjuste/pemu#20]
How to reproduce in pnes 3.40:
- in general options, set:
       scaling = fit 4:3,
       filter = linear
       effect = bilinear filtering
- start a game
      => the filter and effect are not applied
- open game options, change options and set them again just like above
      => now the filter and effect are applied

**Comment by Cpasjuste** [comment]
Fixed in latest releases
