### ISSUE TITLE
rooms de Pgem fica em qual diretorio?

### ISSUE THREAD

**Issue by ReysNelly** [Cpasjuste/pemu#204]

**Comment by joesayegh** [comment]
Oi, para PS4

gamegear - /data/pgen/gamegear/

megadrive - /data/pgen/megadrive/

master system - /data/pgen/sms/

mega-cd (unzipped cue/bin) - /data/pgen/megacd/

**Comment by ReysNelly** [comment]
obrigada

**Comment by joesayegh** [comment]
de nada. pGen 6.5 para PS4 funciona!
