### ISSUE TITLE
UPDATES for switch

### ISSUE THREAD

**Issue by mcbeth1935** [Cpasjuste/pemu#205]
cpasjuste thanks for the updates but i don't see the switch ones, i know you fix the issue for demon's of asterborg, i was waiting for the update of pgen but you didn't upload it

**Comment by Cpasjuste** [comment]
Hi,
Yes sorry the switch build did go wrong, will fix that on Monday (I'm unavailable right now!).

**Comment by Cpasjuste** [comment]
Hi,
It's fixed

**Comment by Vecinagamer** [comment]
Very very thanks @Cpasjuste thanks my friend winderfull crack
