### ISSUE TITLE
Pgen 6.5 switch

### ISSUE THREAD

**Issue by mcbeth1935** [Cpasjuste/pemu#206]
Cpasjuste i downloaded the NRO of pgen 6.5 and has the same issue on demon's of asterborg when i go back, the screen doesn't move and the carácter appears from the other SIDE off the screen

**Comment by Cpasjuste** [comment]
Hi,

I know there is multiple version for this rom, could it be the problem ?

**Comment by mcbeth1935** [comment]
I uploaded the rom in mediafire, im going to paste here the link 
https://www.mediafire.com/file/62ffpfigkezmf7n/Demons_of_Asteborg.bin/file
I have tested this rom on lemuroid for android it works good and in the emulator of sega genesis online on switch and it works very good

**Comment by Cpasjuste** [comment]
Hi @mcbeth1935 , I didn't had the time to take look yet, but I will next week.

**Comment by MayanKoyote** [comment]
When I tested v6.3 on PSVita for scrambled logo and "walking from the other side of the screen" - all versions behaved the same way (all had scrambled logo and "other side walk" bug). So most likely it does not depend on the version of the game.

**Comment by Cpasjuste** [comment]
> I uploaded the rom in mediafire, im going to paste here the link https://www.mediafire.com/file/62ffpfigkezmf7n/Demons_of_Asteborg.bin/file I have tested this rom on lemuroid for android it works good and in the emulator of sega genesis online on switch and it works very good

Hi, are you (really) sure you are using version 6.5 ? Because i just tested it and couldn't reproduce the problem with your file. Also, are you launching pGEN in "non applet mode" (press R when launching a game to load hbmenu) ?

**Comment by mcbeth1935** [comment]
Cpasjuste yes you are right is working fine right now, i always make a forwarder to run a homebrew maybe i restarted the switch and it works, thank you so much 
![20220610_103412](https://user-images.githubusercontent.com/105265145/173102869-070ba75d-96dd-4f58-be7e-79792c529f70.jpg)
![20220610_103544](https://user-images.githubusercontent.com/105265145/173102951-577694a0-646f-43cf-ad6a-10a7fe1b77ff.jpg)
![Uploading 20220610_103449.jpg…]()

**Comment by mcbeth1935** [comment]
![20220610_103544](https://user-images.githubusercontent.com/105265145/173103327-aa392602-88ca-4ddc-8009-e63455eb3fa9.jpg)
