### ISSUE TITLE
PS Vita Build

### ISSUE THREAD

**Issue by tmznix** [Cpasjuste/pemu#21]
Is a current release possible for the ps vita?
I tried to compile it myself but it was impossible
Thank you.
Cheers.

**Comment by mfncl9991** [comment]
+1 - also interested in a current vita build. When compiling get stuck at 

`mark@ubuntu-gui:~/pemu/cmake-build$ cmake -DBUILD_PSP2=ON -DCMAKE_BUILD_TYPE=Release ..
-- Using custom toolchain: Toolchain.cmake
-- Using custom toolchain: /home/mark/pemu/libcross2dui/libcross2d/Toolchain.cmake
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using custom toolchain: /home/mark/pemu/libcross2dui/libcross2d/Toolchain.cmake
-- Using custom toolchain: /home/mark/pemu/libcross2dui/libcross2d/Toolchain.cmake
CMake Error at psnes/CMakeLists.txt:169 (vita_create_self):
  Unknown CMake command "vita_create_self".


-- Configuring incomplete, errors occurred!
See also "/home/mark/pemu/cmake-build/CMakeFiles/CMakeOutput.log".
`

with correct env variables for the psvita sdk install.

**Comment by whmzsu** [comment]
Any prebuild files ready  for ps vita ????

**Comment by mundodisco8** [comment]
I guess there will be no more releases for the Vita... What was the last release for Vita?

**Comment by Cpasjuste** [comment]
Vita build released
