### ISSUE TITLE
pNES v.6.5 Vita NOT WORKING

### ISSUE THREAD

**Issue by chabarga** [Cpasjuste/pemu#211]
pNES Vita show invalid Rom Error. start and select Buttons not working for settings

**Comment by MayanKoyote** [comment]
Try using unzipped roms.

**Comment by MayanKoyote** [comment]
I confirm it. On PSVita pNES v6.5 doesn't want to open zipped roms - Error Invalid File. But opens unzipped roms.
I don't know how it was in previous versions.
Roms were taken from the recommended romset.

**Comment by chabarga** [comment]
My Roms are Working, woked fine on pNES v.5.2 / v.6.1 / 6.4

**Comment by Cpasjuste** [comment]
Hi,

I updated the "libarchive" package a few days ago in the vitasdk packages repo, but I guess it was not available yet when I did the 6.5 release. This will be fixed for next release I guess.

**Comment by chabarga** [comment]
thanks you @Cpasjuste we have been waiting "pNES For Vita" Long time. we hope that will fix next update

**Comment by Vecinagamer** [comment]
Yes please pnes 6.6
