### ISSUE TITLE
Roms not working pls help :(

### ISSUE THREAD

**Issue by Westoonz** [Cpasjuste/pemu#215]
Can someone help me I have the latest build of pfbneo on switch. I just want to know where I can get the roms? I download the roms they show up green. However, when booting up they won’t load. I tried downloading the fba roms ( fba 0.2.97.40) but they don’t show up. They’re mame files.  The marvel vs capcom series. If I’m missing something please tell me thank you.

If you want to email that's fine artback44@gmail.com

**Comment by Westoonz** [comment]
So I downloaded FinalBurn Neo ROM set (2022-05-13)" on archives.org. I used Utorrent to download the big file. Once the download was complete I received a (2020_01_06fbn) folder. I Open the folder up and went into the ROMs folder that had all of the Roms. I Unzipped only the Arcade folder and put it into the FBNeo (6.5) ROMs folder. When I boot it up on the switch I still get a red text from all of the ROMs from the main menu of FBNeo (6.5).What am I missing?

**Comment by Westoonz** [comment]
> Put your folder structure here.
I don't know how to do a folder structure. Do you have a email or discord so I can send you screen shots.

**Comment by Westoonz** [comment]
> Upload pic and put link here

https://imgur.com/a/r2Qb1x3

https://imgur.com/a/r2Qb1x3

https://imgur.com/a/r2Qb1x3

https://imgur.com/a/JI5aZ2C

**Comment by tanaduda** [comment]
Latest pic is inside roms or fbneo forder?

**Comment by Westoonz** [comment]
> Latest pic is inside roms or fbneo forder?

roms

**Comment by Westoonz** [comment]
no Idk I only have it on Switch.  
now they're not showing up 

https://imgur.com/a/3iar4ho

**Comment by Cpasjuste** [comment]
The arcade roms needs to be in "/switch/pfba/roms". If it's right and they are not showing up, you may need to delete the "/switch/pfba/config.cfg" file to revert to default values.

**Comment by Westoonz** [comment]
Ok, does the arcade file need to be a zip when putting it in the  "/switch/pfba/roms"?

**Comment by Westoonz** [comment]
> Ok, does the arcade file need to be a zip when putting it in the "/switch/pfba/roms"?

I deleted the config.cfg nothing is still showing up. I'm using pfbneo(6.5) arcade folder in the ROMs folder.

**Comment by Cpasjuste** [comment]
> > Ok, does the arcade file need to be a zip when putting it in the "/switch/pfba/roms"?
> 
> I deleted the config.cfg nothing is still showing up. I'm using pfbneo(6.5) arcade folder in the ROMs folder.

No, the zipped files goes in the "roms" folder directly.

**Comment by Westoonz** [comment]
> Give me your email

artback44@gmail.com

**Comment by Westoonz** [comment]
> > > Ok, does the arcade file need to be a zip when putting it in the "/switch/pfba/roms"?
> 
> > 
> 
> > I deleted the config.cfg nothing is still showing up. I'm using pfbneo(6.5) arcade folder in the ROMs folder.
> 
> 
> 
> No, the zipped files goes in the "roms" folder directly, not in "roms/arcade". As I said previously, put your arcade roms (zip files) in "/data/pfba/roms". For consoles, for example master system, put your zipped files in "/data/pfba/sms" folder.
> 
> Take a look at the readme linked before for other roms paths.


So I download the (PFBNEO 6.5) on the Switch itself. I don't see a data folder when I boot up on my computer. I just see a ROMS folder. Inside the folder are all of the zipped ROMS of the games. 


Switch/pfbneo/ROMs/zip of all arcade games) that's it. 

When I load Pfbneo on switch. No roms. I deleted the config.cfg. No roms. 

I deleted everything and start over with the same results. 

Now I'm going to try downloading the Pemu-master.

**Comment by Westoonz** [comment]
> > > Give me your email
> 
> > 
> 
> > [artback44@gmail.com](mailto:artback44@gmail.com)
> 
> 
> 
> check it

I didn't get anything yet.

**Comment by Westoonz** [comment]
> > > > Give me your email
> > 
> > > 
> > 
> > > [artback44@gmail.com](mailto:artback44@gmail.com)
> > 
> > 
> > 
> > check it
> 
> got it was in my spam

**Comment by Westoonz** [comment]
> > > > > Give me your email
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > [artback44@gmail.com](mailto:artback44@gmail.com)
> > > 
> > > 
> > > check it
> > 
> > 
> > got it was in my spam

https://imgur.com/a/bKwx467

https://imgur.com/a/p3L5lp1

https://imgur.com/a/1MWhW0I

https://imgur.com/a/OTOR9AG

**Comment by tanaduda** [comment]
> > > > > > Give me your email
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > [artback44@gmail.com](mailto:artback44@gmail.com)
> > > > 
> > > > 
> > > > check it
> > > 
> > > 
> > > got it was in my spam
> 
> https://imgur.com/a/bKwx467
> 
> https://imgur.com/a/p3L5lp1
> 
> https://imgur.com/a/1MWhW0I
> 
> https://imgur.com/a/OTOR9AG
> 
> Nothing at this point you might as well just give me the switch files that work and all donate to you guys.

You cannot unzip.

**Comment by Westoonz** [comment]
> > > > > > > Give me your email
> > > > > 
> > > > > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > > [artback44@gmail.com](mailto:artback44@gmail.com)
> > > > > 
> > > > > 
> > > > > check it
> > > > 
> > > > 
> > > > got it was in my spam
> > 
> > 
> > https://imgur.com/a/bKwx467
> > https://imgur.com/a/p3L5lp1
> > https://imgur.com/a/1MWhW0I
> > https://imgur.com/a/OTOR9AG
> > Nothing at this point you might as well just give me the switch files that work and all donate to you guys.
> 
> You cannot unzip.

this time I didn't unzip it's still not working.

**Comment by tanaduda** [comment]
Search for /pfba/roms instead /pfbneo/roms folder.

**Comment by Westoonz** [comment]
Cpasjuste

do you the have latest build of **PFBA ON SWITCH** 

because the latest build is PFBNEO (6.5) and that's not working

**Comment by tanaduda** [comment]
> Cpasjuste
> 
> do you the have latest build of **PFBA ON SWITCH**
> 
> because the latest build is **PFBNEO** (6.5) and that's not working

This is the latest atm.

**Comment by Westoonz** [comment]
Welp I'm going to take a break . thank you guys so much for helping me all keep you posted if it works.

**Comment by Cpasjuste** [comment]
> Cpasjuste
> 
> do you the have latest build of **PFBA ON SWITCH**
> 
> because the latest build is **PFBNEO** (6.5) and that's not working

Sorry but it's working for everyone, you are doing something wrong :/

**Comment by Westoonz** [comment]
> > Cpasjuste
> > do you the have latest build of **PFBA ON SWITCH**
> > because the latest build is **PFBNEO** (6.5) and that's not working
> 
> Sorry but it's working for everyone, you are doing something wrong :/

Yeah, I honestly don't know what I'm doing wrong. Its all good all figure it out thanks.

**Comment by Westoonz** [comment]
> > > Cpasjuste
> 
> > > do you the have latest build of **PFBA ON SWITCH**
> 
> > > because the latest build is **PFBNEO** (6.5) and that's not working
> 
> > 
> 
> > Sorry but it's working for everyone, you are doing something wrong :/
> 
> 
> 
> Yeah, I honestly don't know what I'm doing wrong. Its all good all figure it out thanks.

So I finally got it to work but it's the 5.1 version. Do you know where I put the preview thumbnails in the pbfneo folder? 


(also I donated some money in your kofi)

**Comment by Cpasjuste** [comment]
Thanks for your support @Westoonz
