### ISSUE TITLE
Pnes rom list wont appear on switch.

### ISSUE THREAD

**Issue by rooster87** [Cpasjuste/pemu#216]
Hi i  installed Pnes and added the roms and artworks but when i open the emu on switch the list wont pop up?? i put the roms where it supposed to be created the folder and for the artworks also.

**Comment by angomania** [comment]
... can't reproduce. PNes is running fine on my switch and previews images & videos are shown.

Installation on switch (The directories may have to be created):
- copy "pnes.nro" to "/switch/pnes" directory on sdcard
- copy roms to "/switch/pnes/roms/" directory on sdcard
- copy preview images to "/switch/pnes/roms/media/mixrbv2" directory on sdcard
- copy preview videos to "/switch/pnes/roms/media/video" directory on sdcard

**Comment by rooster87** [comment]
> ... can't reproduce. PNes is running fine on my switch and previews images & videos are shown.
> 
> Installation on switch (The directories may have to be created):
> 
> * copy "pnes.nro" to "/switch/pnes" directory on sdcard
> * copy roms to "/switch/pnes/roms/" directory on sdcard
> * copy preview images to "/switch/pnes/roms/media/mixrbv2" directory on sdcard
> * copy preview videos to "/switch/pnes/roms/media/video" directory on sdcard

![Uploading IMG_20220702_105741386.jpg…]()

**Comment by rooster87** [comment]
I did all that heres the pics see if u can notice something i did wrong and i only want the artworks and i didnt put preview vids takes alot of space.
![IMG_20220702_110043580](https://user-images.githubusercontent.com/47829443/177006093-191bc9de-85e4-439d-a1d1-c08a29b56fcb.jpg)

![IMG_20220628_160548473](https://user-images.githubusercontent.com/47829443/177006078-2671b4ac-4f8e-4ff6-82d5-aaabaec8bcc0.jpg)
![IMG_20220702_105751957](https://user-images.githubusercontent.com/47829443/177006068-7ed320ba-3f1d-4e35-a3e7-ae92d7b9b0f0.jpg)

**Comment by rooster87** [comment]
![IMG_20220702_105741386](https://user-images.githubusercontent.com/47829443/177006277-1a7bbbc6-7add-4b28-9a4c-a41a3a84ed7f.jpg)
![IMG_20220702_105751957](https://user-images.githubusercontent.com/47829443/177006364-36a97d39-6353-4ff5-94f8-45362dba4b20.jpg)
![IMG_20220628_160548473](https://user-images.githubusercontent.com/47829443/177006371-06f661fe-0232-4556-95ba-4d74137084f6.jpg)
![IMG_20220702_110043580](https://user-images.githubusercontent.com/47829443/177006376-e8eafd22-7b26-4ed8-9823-4bb88efca01c.jpg)

**Comment by rooster87** [comment]
Here i re upload the pics

**Comment by angomania** [comment]
Did you copy **all** roms to the switch?

Also look into: **Main Options** - **Main** - **View**   and select ALL.
If you select AVAILABLE or FAVORITES and the rom does not exist in the rom folder, the preview wouldn't shown.

**Comment by Cpasjuste** [comment]
Hi,

Also:

-  Are you loading the emulator in "non applet mode" (with all available memory) ?
- Are you using a FAT32 formatted sd-card ?

**Comment by rooster87** [comment]
> 

I might have to try to delete that file and see ot works. Thank you ill keep u posted.

**Comment by rooster87** [comment]
> Hi,
> 
> Also:
> 
> * Are you loading the emulator in "non applet mode" (with all available memory) ?
> * Are you using a FAT32 formatted sd-card ?
> * Finally, try to delete the "/switch/pnes/config.cfg" file

Hi juste i figured it out that both file config.cfg and gamelis.xml must be deleted both to make it work i suggest you when u update the app to put a note for that and i appreciate your good work of these app keep it up my friend thank you😊🤘.

**Comment by rooster87** [comment]
Yes i used on applet mode and yes my micro sd card is on fat32 format im a
noob about the jailbreak i just followed a tutorial on youtube for emmunand
for sd card and follow it to be fat32 so should i use it on exfat to make
it work without the applet mode?
