### ISSUE TITLE
roms list is not showing in PSNES version of psvita

### ISSUE THREAD

**Issue by xprgcjj** [Cpasjuste/pemu#217]
*psnes version 6.5 of psvita, the list of roms is not showing

*the same thing happens in the most current pgen, it doesn't show the list of roms

*in the most current pnes the list of roms appears but it does not run the game, it has a failure when running the game

**Comment by xprgcjj** [comment]
Could you please port these emulators to the Wii u?
it would be nice to have them on the wii u

thanks

**Comment by MayanKoyote** [comment]
> *the same thing happens in the most current pgen, it doesn't show the list of roms

pGEN v.6.5 for PSVita shows a list of roms without problems

> *in the most current pnes the list of roms appears but it does not run the game, it has a failure when running the game

https://github.com/Cpasjuste/pemu/issues/211

**Comment by knerlington** [comment]
Can confirm that roms aren't shown in the PS Vita build of this.
Version 6.5 of pSNES.
Individual zip files or the romset referenced elsewhere doesn't show up. Neither does unzipped .sfc or .smc files.

**Comment by Cpasjuste** [comment]
Hi,

Yes, something changed in one of the latest releases (db files are first loaded from sdcard then romfs, so if an old db file is on the sdcard (data folder) it can go wrong.
