### ISSUE TITLE
error driver init failed

### ISSUE THREAD

**Issue by otidki** [Cpasjuste/pemu#22]
Good I have put the pfba 3.4 and when I run neogeo games it says:
 error
 driver init failed

Neogeo games as metal slug, before in previous versions it worked fine, the strange thing is that now with previous version of pfba it also works fail

 I'm at 8.10 with atmosphere 0.9.3 with hbmenu 3.1.0 and nxhbloader 2.2.0

My bio is like this:

http://img4.imagetitan.com/img.php?image=20_bio.jpg

 knows the solution, thanks

**Comment by rval735** [comment]
It happened something similar to me when trying to load CPS-2/3  (ex. mvsc or sfiiin), pFBA showed "driver init failed". However, when loading NeoGeo games (ex. KoF), those were running fine.

My setup is: 9.0.1; Atmosphere 0.9.4js; HBMenu 3.1.1, NXHBLoader 2.2.0

**Comment by bamboomix** [comment]
Same "driver init failed" on some CPS-1/2 roms
For exemple, 1941 europe version craches, but the japanese one loads correctly, both roms from a good FBA romset.
Hope that can help, however great emulator, merci mec ! :)

Switch 9.2 - SXos 2.9.4

**Comment by Cpasjuste** [comment]
Hi,

i do not have this problem on latest version, both roms works fine.
