### ISSUE TITLE
Provide dats for all Emulators?

### ISSUE THREAD

**Issue by s3phir0th115** [Cpasjuste/pemu#222]
Hello,

I'd like to use these emulators, but aside from FBneo, none of them appear to provide the dats that they were built upon, and they recommend using said dats.

When you go to No-Intro's dat-o-matic or redump, only the newest dats are provided now, and finding the old dats that are advised is difficult. Most romsets don't provide them either from what I'm seeing, just saying to go to the upstream source.

Can all the dats be provided, if you have them?

**Comment by tanaduda** [comment]
Only FBNeo need it:

https://github.com/libretro/FBNeo/tree/ae96b110c5938a48a9d712e04ce3a542e74ee186/dats
