### ISSUE TITLE
pNES for Windows no-intro rom names do not match media file names in gamelist

### ISSUE THREAD

**Issue by bahgee** [Cpasjuste/pemu#227]
I'm using the NES no-intro romset and media I download from pEMU git a while ago (for the Switch version).  There is a mismatch between rom names and media.  For example, for the game Batman Returns - the rom is named Batman Returns (Europe).zip, but the media it is looking for is named is named Batman Returns (Unknown) (Beta).png so it doesn't display art or video.  This is how it looks in the gamelist.xml:

game id="3520035609">
        path>Batman Returns (Europe).zip</path>
        name>Batman Returns</name>

      image type="mixrbv2">media/mixrbv2/Batman Returns (Unknown) (Beta).png</image>
      video type="video">media/video/Batman Returns (Unknown) (Beta).mp4</video>

The files in the media folder are named correctly for this rom - Batman Returns (Europe).png  There are many issues like this and it si the same in the switch version as well.  Can the gamelist be updated so the rom names match the image and video files?

**Comment by Cpasjuste** [comment]
Hi @bahgee.
I'm sorry but i think you'll need to re-download previews images and videos since the way it's handled internally changed. This was done to lower the media zip files sizes.

**Comment by bahgee** [comment]
Hi. Thanks for the response!  I really like your emulators.   Do you have links to the NES media?  The ones I found on your git don’t work anymore. Thanks again!
________________________________

**Comment by Cpasjuste** [comment]
Ho yes, it seems there's a bug on my website, i need to check that. In the meantime you should be able to right click on the link and "save as".

**Comment by bahgee** [comment]
Never mind. Got the link to work and it displays art and video for all games now.
________________________________

**Comment by bahgee** [comment]
Yes, that is what I did!
________________________________
