### ISSUE TITLE
PSNES for Vita 

### ISSUE THREAD

**Issue by danny199012** [Cpasjuste/pemu#228]
Not showing up any ROMs at all I oddly don't have this issue with PNES or PGEN ROMs are in correct directory I have tried .zip and .smc and .sfc
Hopefully this could be fixed I'm willing to test any new builds if need a tester unless there has to be a specific format 
Also literally using the latest build of each Emu

**Comment by Cpasjuste** [comment]
Hi,

Do you have a "gamelist.xml" file (or something like this) in your data folders (/switch/pnes, /switch/psnes/ ...)? If so, can you try to delete them ?

**Comment by pnvnd** [comment]
Renaming / deleting `gamelist.xml` worked for me, thanks!
