### ISSUE TITLE
rompath not working?

### ISSUE THREAD

**Issue by tommy96814** [Cpasjuste/pemu#229]
only pgen is working the other three can't find the roms even with correct path and deleted config file or pointed to the correct path. switch version.

**Comment by Cpasjuste** [comment]
Hi,

Do you have a "gamelist.xml" file (or something like this) in your data folders (/switch/pnes, /switch/psnes/ ...)? If so, can you try to delete them ?

**Comment by andercard0** [comment]
> Hi,
> 
> Do you have a "gamelist.xml" file (or something like this) in your data folders (/switch/pnes, /switch/psnes/ ...)? If so, can you try to delete them ?

Hi. Deleting this xml works for me. Thank you. 
Also, is possible to use another path for roms instead of : /switch/pnes/roms ?
