### ISSUE TITLE
PS4 Port , is it possible to put the roms inside the pkg itself ?

### ISSUE THREAD

**Issue by mustafaabdd1000** [Cpasjuste/pemu#231]
so ps4 is really bad dealing with hundreds of roms and icon , it will take ton of time to copy thats number of files 

wether using ftp or ps4 file manager

it will be very helpful if there is a possibility to put the roms and icon inside the pkg itself

 so we don't need to go through the process of copying them to the internal hard drive 

and thank you for your excellent work

**Comment by MayanKoyote** [comment]
Elementary. It's open source project. Just fork it, rewrite code to anything you need, fill it to the eyeballs with your favorite pirated roms and build pkg yourself. Profit!
