### ISSUE TITLE
Filter_consolas

### ISSUE THREAD

**Issue by Vecinagamer** [Cpasjuste/pemu#235]
Buenas tardes.
The filter_system console could be added back as it was before, msx1, msx2.spectrum, pc_engine, master_system.
In version 4.4 FBNEO 0.2.97.44 all work fine, but there is a memory leak and the covers_png disappears due to lack of memory consumed. Thanks for your great work @cpasjuste

**Comment by Cpasjuste** [comment]
Hi,

Are you talking about the vita version? If so, console games won't be added back as fbneo is now too "big" (in term of memory) for the vita to include every systems.
