### ISSUE TITLE
PNes not able to save in game battery file

### ISSUE THREAD

**Issue by Nono0000** [Cpasjuste/pemu#239]
Hello,
With latest version 6.6 of pnes, games like Zelda or Zelda 2 could not save their state using the in-game option.
Of corse the emulator "save state" option is working.
I tried to create folder "battery", "battery saves" or battery ram" folders but it did not change anything.
Can you have a look?
Thanks

**Comment by MayanKoyote** [comment]
I confirm this. SRAM saves are not created. At least for the PSVita version 6.6.
ROMs are from the recommended source, the SRAM (battery) flag is present in the headers.

**Comment by Cpasjuste** [comment]
Hi,

Thanks for the report, this is fixed in af057c7f6a6f6da2a5ad13fd343dfe7806b0f5b2 (available in next release)
