### ISSUE TITLE
Buttons do not respond. Am on Switch FW 9.0.0.

### ISSUE THREAD

**Issue by nanashi89** [Cpasjuste/pemu#24]
I am on Switch FW 9.0.0. In case you've been out of the loop, homebrew created before that update has button input disabled. Can you recompile and post a revision, please?

Thanks!

**Comment by ituligadj** [comment]
Same issue here, I use a forwarder to get to the homebrew and it launches fine but controls do not respond. If I go through the HBMenu it works fine, though... could you have a look-see?

**Comment by CrJack64** [comment]
Any chance to have pNES and pSNES update for FW 9?  Thank you!

**Comment by chronoss09** [comment]
Samething for me, pNES and pSNES dont work on 9.x :(

**Comment by Cpasjuste** [comment]
Needs to update them, will do it someday (when i find the time to do so, it require some work)

**Comment by Cpasjuste** [comment]
Hi, 

It's fixed in latest releases.
