### ISSUE TITLE
pGen, pNES, pSNES v6.6 config.cfg show VERSION = 605 (instead of 606)

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#240]
_I can only run pGen, pNES, pSNES on PSVita now. Therefore, I do not know if this applies to any pGen, pNES, pSNES variants or if it is typical only for PSVita._
pGen, pNES, pSNES (maybe others too) v6.6 config.cfg show "VERSION = 605" (instead of 606).
For previous versions this was more predictable: 604 for v6.4, 605 for v6.5.
This makes it harder to guess installed version.

**Comment by Cpasjuste** [comment]
Hi,

This was a mistake, it will be fixed in next release, thanks!
