### ISSUE TITLE
pGen, pNES, pSNES v6.6 for PSVita - no version information in template.xml and/or param.sfo files

### ISSUE THREAD

**Issue by MayanKoyote** [Cpasjuste/pemu#241]
pGen, pNES, pSNES (maybe others too) v6.6 for PSVita - do not contain version number information in template.xml and/or param.sfo files.
This makes it difficult to guess which version is installed.

**Comment by Cpasjuste** [comment]
Hi, this should be fixed in next release, thanks. (654b597ab295c9d28296bfdb2f924434218d97fc)
