### ISSUE TITLE
[Feature Request] Support for RecalBox formatted gamelist.xml

### ISSUE THREAD

**Issue by shinji257** [Cpasjuste/pemu#244]
I don't know how possible this is (or if you even will... I'd understand if not) but would it be possible to support a gamelist.xml generated from Skraper instead?

I know that you said you use sscrap to generate the gamelist.xml files but I can't get it built in order to generate the files myself.

**Comment by Cpasjuste** [comment]
Hi,

Did you try a recalbox gamelist.xml yet (put your gamelist.xml "override" file in data folder)? I think it may work out of the box (with some missing information).

**Comment by Cpasjuste** [comment]
Hi, you'll have to test again with next release comes out, i fixed a few things and it may work better.

**Comment by Cpasjuste** [comment]
Hi,

This should be fixed in [latest release](https://github.com/Cpasjuste/pemu/releases/tag/v6.7), please let me know if it's not the case so i can re-open this issue!
