### ISSUE TITLE
Preview images and videos links are broken

### ISSUE THREAD

**Issue by Muhammad-Adam** [Cpasjuste/pemu#247]
Clicking on all the links for the preview images and videos does nothing. Possible that the link is dead.

**Comment by Cpasjuste** [comment]
Hi @Muhammad-Adam ,
I think it should work if you right click to download ? A problem with the site not on SSL. I'll try to fix that in the next days/weeks.

**Comment by Muhammad-Adam** [comment]
I did try right clicking and open a new tab. The tab quickly disappears after a few milliseconds.

**Comment by Muhammad-Adam** [comment]
I tried on my phone, the link works. I will try again with my pc later when I have access. I will update this ticket later on. Thank you.

**Comment by Muhammad-Adam** [comment]
Update: It is possible to download. Need to `right-click` and the click `save link as`.
