### ISSUE TITLE
Possibility to hide empty platforms

### ISSUE THREAD

**Issue by artik** [Cpasjuste/pemu#254]
I'm using this emu a lot, but only for `Neogeo` and `CPS1/2/3`. Is there a way to hide empty platform sections?

**Comment by Cpasjuste** [comment]
Hi,

This is a good idea, I'll try to implement that for the next release.

**Comment by Cpasjuste** [comment]
Hi,

This was added in this commit and will  be available for next release: https://github.com/Cpasjuste/pemu/commit/6ea8560dc95d1a5a24978e27eb8d6b490367b20b

For information, an new option was added: "GUI_SHOW_AVAILABLE". If set to "ON", roms not found in roms paths won't be added at all from gamelist (as theire respective systems etc..).

**Comment by artik** [comment]
Fantastic, thanks for your work

**Comment by Cpasjuste** [comment]
Hi,

This should be fixed in [latest release](https://github.com/Cpasjuste/pemu/releases/tag/v6.7), please let me know if it's not the case so i can re-open this issue!
