### ISSUE TITLE
Cover issue

### ISSUE THREAD

**Issue by mcbeth1935** [Cpasjuste/pemu#255]
I have the roms of arctraiser 1 and 2, so i have the version of psnes 4.4 at first it runs very well but for the constant updates of the firmware of nintendo switch the emulator psnes started to have grafical issues, i update the emulator to 6.5 version and the grafical issues still there 
![20230615_230537](https://github.com/Cpasjuste/pemu/assets/105265145/72d68c76-ae46-41ae-8c67-c0f9294a711d)

**Comment by Cpasjuste** [comment]
Hi,

This should be fixed in [latest release](https://github.com/Cpasjuste/pemu/releases/tag/v6.7), please let me know if it's not the case so i can re-open this issue!
