### ISSUE TITLE
Wii support needed if possible

### ISSUE THREAD

**Issue by Ntemis** [Cpasjuste/pemu#260]
1st lets start with a BIG thank you for your wonderful work.I have been using it every single day on all my devices.
And as the title says would you be kind enough to add wii to supported devices as well?
Would really be amazing and thanks again

**Comment by Cpasjuste** [comment]
Hi,

I don't own a Wii, and I think it may require some work to do the porting, I don't think I have the courage to do so.

Sorry mate!
