### ISSUE TITLE
Lion king slow

### ISSUE THREAD

**Issue by mcbeth1935** [Cpasjuste/pemu#268]
![IMG_20231023_113740](https://github.com/Cpasjuste/pemu/assets/105265145/78feb1a4-b8d7-4275-8e0d-cfa162f1021a)
I've tested lion king on psnes switch versión 6.6, 6.7.1 and both are slow When i rearch the top to figth the hyena the FPS goes to 50 it continues to second stage at 50 fps i've tested the 4.4 versión and it goes very good i leave some pictures of the Game in versión 6.7.1
![IMG_20231023_113254](https://github.com/Cpasjuste/pemu/assets/105265145/0f996de7-bdd8-4e15-9241-de1daf13d0c4)
![IMG_20231023_113716](https://github.com/Cpasjuste/pemu/assets/105265145/6480ca4a-1bb9-4380-8c3f-b80f0f2a0edc)

**Comment by Cpasjuste** [comment]
Hi,

I can see that you are using a "high res" shader which may be slow. Are you sure you were using the same shader when you tried on 4.4 ?

**Comment by mcbeth1935** [comment]
The shader si diferent in 4.4 i've used sharp-2xsal, in 6.7.1 sharp-xbrz-freesca it goes slow but When i put sharp-2xsal it goes well, You are rigth i think the problem is the shader
![IMG_20231030_115814](https://github.com/Cpasjuste/pemu/assets/105265145/18185737-d7e3-436d-9d56-01a4343a5d45)

![IMG_20231030_115734](https://github.com/Cpasjuste/pemu/assets/105265145/b58812de-6b0e-41cd-a493-39cfb696bb47)

![IMG_20231030_115213](https://github.com/Cpasjuste/pemu/assets/105265145/3f4a157b-d699-40b3-83a1-6b0f70717010)
![IMG_20231030_114927](https://github.com/Cpasjuste/pemu/assets/105265145/ab9bfa73-486f-4362-8be2-b35b1913608a)
![IMG_20231030_115135](https://github.com/Cpasjuste/pemu/assets/105265145/cc72fd61-94ba-4570-9f25-c0070c961a72)
