### ISSUE TITLE
Preview images and videos

### ISSUE THREAD

**Issue by tienviplaanh** [Cpasjuste/pemu#269]
Thanks for your project, But I want to install preview images and videos for all types of roms
Can you give me the link?

**Comment by angomania** [comment]
I've noticed too that all download links are gone. Maybe it's a copyright thing ... 

You can find old links on the internet archive wayback machine ;)

**Comment by tienviplaanh** [comment]
> I've noticed too that all download links are gone. Maybe it's a copyright thing ...
> 
> You can find old links on the internet archive wayback machine ;)
But I can't find any link with a working video preview; all links are dead.

**Comment by tienviplaanh** [comment]
> But I can't find any link with a working video preview; all links are dead.

But I can't find any link with a working video preview; all links are dead.

**Comment by tienviplaanh** [comment]
> I've noticed too that all download links are gone. Maybe it's a copyright thing ...
> 
> You can find old links on the internet archive wayback machine ;)

But I can't find any link that has a working video preview; all links are dead.

**Comment by gavinliu** [comment]
The preview image and video are generated by [skraper](https://www.skraper.net/), so you can make it by yourself.
