### ISSUE TITLE
Previews not downloading

### ISSUE THREAD

**Issue by toatahu116** [Cpasjuste/pemu#273]
The download links for the pgen previews does not work. could you please update it?

**Comment by tienviplaanh** [comment]
true, I have found on the internet, but it's not fully (video+picture)

**Comment by drkjpgc** [comment]
mixrbv2 please

**Comment by Cpasjuste** [comment]
Hi guys,

The previews and such are not provided anymore, you have to use something like "skraper" to build your "gamelist.xml" files and retrieve previews.
