### ISSUE TITLE
Problems with Arkanoid on Nintendo Switch with PFBNeo

### ISSUE THREAD

**Issue by erikop87** [Cpasjuste/pemu#37]
Hello good afternoon, is it possible to configure the controls from left to right in this rom of Taito?
Having the original cabinet a wheel, I would like to know if it is possible to make this type of configuration.
Thanks greetings.

**Comment by lineacero** [comment]
Please arkanoid pfba

**Comment by Cpasjuste** [comment]
Hi, it seems to work in latest version (5.0), but sensitivity is not good. I'll try to take a closer look someday.
