### ISSUE TITLE
pSNES 3.4 and D-Pad issues

### ISSUE THREAD

**Issue by azoreseuropa** [Cpasjuste/pemu#39]
The latest atmosphere and pSNES 3.4. The same for pNES.. D-Pad is no responsive. I can't used it for my latest atmosphere, help ?

**Comment by Dumbassahedratron** [comment]
I am unable to interact with pSNES at all using any of the buttons, D-Pad included. I would have opened a new issue but mine seems similar to the OP's.

**Comment by azoreseuropa** [comment]
What can we do about it ? I hope this fix because I love pSNES. Nice design and everything. Please fix it. Many people report cannot used it because of D-Pad issues. Only SX OS users said it works fine for them. Not Atmosphere users like us.

**Comment by chronoss09** [comment]
It work for me :
Atmo 1.10.5
FW 9.0.1

**Comment by azoreseuropa** [comment]
> It work for me :
> Atmo 1.10.5
> FW 9.0.1
> 
> For averyone, use the latest pSNES 4.3

It was worked for me like you until I used to 9.1.0 and it doesn't worked anymore.

**Comment by Cpasjuste** [comment]
Hi,

It should work if you delete the config.cfg file, I guess I did some crap in one of the latest changes.
