### ISSUE TITLE
pFBA favorites cleared/overwritten after restart

### ISSUE THREAD

**Issue by jskuby** [Cpasjuste/pemu#4]
I’m trying to set up a favorites list in pFBA 3.3 and the list works as I build it, but after a restart one of two things happens: either my list gets cleared out or if I add any more games the next time I restart I only have the latest additions and previous favorites are gone. 

More detail: if I leave the selected list as favorites everything is fine. However if I switch to working or all then exit, that is when the favorites are cleared.

**Comment by Cpasjuste** [comment]
Hi,

I'm unable to reproduce the problem, are you using exFAT sdcard?

**Comment by jskuby** [comment]
I am using FAT32.  I can repeated produce the issue. At this point I just back up my fav file in case it gets cleared. But adding to it will clear it again.

**Comment by kabihuni** [comment]
When you remove any of your favorite lists and restart then,all of your favorites disappear.

**Comment by Cpasjuste** [comment]
This should be fixed in latest releases. Feel free to re-open the issue if it still persist.
