### ISSUE TITLE
Build Issues on Ubuntu (18.04.4 LTS) for a nintendo switch. 

### ISSUE THREAD

**Issue by sbmotoracer** [Cpasjuste/pemu#40]
Good Evening, 

I'm having issues building the code. make errors out stating that mpv/client.h doesn't exist. 

[ 10%] Building CXX object ui/CMakeFiles/cross2dui.dir/c2dui_ui_romlist_classic.cpp.obj
In file included from /mnt/64110fa9-b406-4666-9a86-ce90471185ce/transfer2/NinSwitchHomeBrew/SnesEmulator/pemu/ui/c2dui_ui_romlist_classic.cpp:10:
/mnt/64110fa9-b406-4666-9a86-ce90471185ce/transfer2/NinSwitchHomeBrew/SnesEmulator/pemu/ui/mpv.h:11:10: fatal error: mpv/client.h: No such file or directory
   11 | #include <mpv/client.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
ui/CMakeFiles/cross2dui.dir/build.make:374: recipe for target 'ui/CMakeFiles/cross2dui.dir/c2dui_ui_romlist_classic.cpp.obj' failed
make[2]: *** [ui/CMakeFiles/cross2dui.dir/c2dui_ui_romlist_classic.cpp.obj] Error 1
CMakeFiles/Makefile2:336: recipe for target 'ui/CMakeFiles/cross2dui.dir/all' failed
make[1]: *** [ui/CMakeFiles/cross2dui.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I've tried:  
install recent mpv library from ppa:
sudo add-apt-repository -y ppa:mc3man/bionic-media
sudo apt-get -y install libmpv-dev

 I have also installed libmpv-dev and still get the error.

Can someone tell me what I'm missing here? Thank you.

**Comment by Cpasjuste** [comment]
There is some undocumented stuff to do for the switch build, and my time is very limited. So those steps are not detailed... It will be hard if you're not an experimented switch developer. Anyway, you need https://github.com/Cpasjuste/pacman-packages/commits/switch-libmpv to build and install libmpv for the switch, and you'll also need to use an old sdl2 package (0.18 if i remember).
