### ISSUE TITLE
ROMs not displaying in directory

### ISSUE THREAD

**Issue by roflcopter777** [Cpasjuste/pemu#43]
PS Vita, latest version of HenKAKU, installed psnes folder to ux0:/data/psnes/roms but ROM files refuse to display after installing to SD card. I transferred them via FTP over WiFi using Vitashell and they simply don't show up. Is this an known issue or am I doing something wrong?

**Comment by MindFvck** [comment]
I have my roms in .zip form and can run fine but have no preview image. When I extract them they don't run but I do have preview image. Any fix on this?

**Comment by roflcopter777** [comment]
Disregard, the issue was that they weren't in zip file. I don't know why the instructions didn't mention this.

**Comment by MindFvck** [comment]
Where you able to get the preview images to show for the games?

**Comment by roflcopter777** [comment]
No, but that's not an issue for me, but I wasn't able to achieve full speed without frameskip. Not dumping on the emulator, but the Vita's quirky CPU.
