### ISSUE TITLE
I can't see my rons in psnes 4.3

### ISSUE THREAD

**Issue by rogeriosm** [Cpasjuste/pemu#45]
I have rom in switch/psnes/rom.
thanks for excelente job

**Comment by Cpasjuste** [comment]
Hi,

Did you figured it out ?

**Comment by Cpasjuste** [comment]
Please use forums to get help about this.

**Comment by rogeriosm** [comment]
sorry I was in personal trouble. roms don't work on .smc only on .zip or .rar
this is not a problem i just took to find out
I'm not English I hope you understand what I wrote
