### ISSUE TITLE
pfba 4.4 crashes on PS Vita

### ISSUE THREAD

**Issue by coestergaard** [Cpasjuste/pemu#48]
The new version 4.4 of pfba seems to crash as soon as it is opened on a Vita.
I have tried it on both my PS Vita and my PSTV with same result.
I have tried to reinstall it but nothing helped.
psnes 4.4 works just fine.

Another user at gbatemp.net has confirmed the same behavior.
Thanks for your support.

**Comment by alfiones** [comment]
Same issue here. I have tried with my PSvita Slim (with sd2vita) and PSvita FAT3G (with original memory card).

Thanks

**Comment by coestergaard** [comment]
Works fine after being fixed. Just download again and install the lastest build.

**Comment by lineacero** [comment]
La nueva versión 4.4 de pfba parece fallar tan pronto como se abre en una Vita.
