### ISSUE TITLE
switch: pfba 4.4 preview picture doesn't appear and driver init failed by fast scrolling gamelist up and down several times.

### ISSUE THREAD

**Issue by haozi168** [Cpasjuste/pemu#49]
Hi, 
Very glad to see pemu 4.4 on switch.
Everything is normal at beginning, when selecting game in pfba ui window, preview picture disappears after fast scrolling game list up and down, using the left and right button. And when this happens, the message "ERROR  DRIVER INIT FAILED" jump out if I want to start the game , and it can't start. However the pnes and psnes works fine after scrolling the  gamelist.
The romset for my pfba 4.4 is full romset 0.2.97.44 SVN  8843, with recommend preview png and mp4 files fully downloaded.
Many thanks for your effort and hoping for solution.

**Comment by alfiones** [comment]
Same error “DRIVER INIT FAILED” with a nes rom and pfba for PSvita. I have tried the last fixed 4.4 vita package of pfba on a Vita slim and on a Fat one.

On my Switch psnes and pnes work fine but pfba has the same driver init error.

**Comment by Cpasjuste** [comment]
@haozi168 , i'm unable to reproduce your problem. So i have some questions:

- Are you using an exFAT formatted sdcard ?
- Does the "ERROR DRIVER INIT FAILED" game works sometime ?

**Comment by alfiones** [comment]
Can i try to answer your questions?
- My PSvita Slim and Fat have a microSD with exFAT 64kb cluster size ;
- My Switch has a microSD with a FAT32 32kb cluster size;
- The "DRIVER INIT FAILED " error appears when i try to start any NES rom with pfba

**Comment by Cpasjuste** [comment]
Hi,

@haozi168 didn't specifically talk about nes roms, so I didn't understand that. @alfiones, do you understand that you need fbneo nes romset, you can't load any nes rom around (while I guess it may work for some).

**Comment by alfiones** [comment]
@Cpasjuste ah ok i’m sorry, I thought it was the same "DRIVER INIT FAILED" error. I just wanted to find a way to emulate nes roms on PS Vita. Retroarch is really too heavy and i don’t want to use it. I noticed that pnes doesn't exist for this console...

**Comment by haozi168** [comment]
@Cpasjuste  Sorry for my late reply.
1. My SD card is 400GB exFAT type.
2. After the DRIVER INIT FAIED appears, all the game in ui list never works. This only happens in Pfba, no matter nes console or arcade. This problem never happens  in Pnes and Psnes during my testing.

Also at that time I noticed that my NS firmware version is 8.1. I have upgrade the firmware to version 9.2 yestoday . And after about 2 days testing, this problem never happens again. So I believe that this is a version related problem. 
There is still a minor bug in 9.2,  which is, after start game(nes or arcade, I just only testing those two consoles) in Pfba, sometimes the audio mutes, and video goes fine. After exit to UI and restart the game, the OS shows that the software error occurs and needs to be close and return to NS ui. Restart Pfba, then everything gets OK. But this may another problem to be discussed.

Anyway, thanks guys.

**Comment by Cpasjuste** [comment]
Hi,
All your "problems" comes from your exfat sdcard. Exfat is not stable with homebrews. I know it's probably not the best approach for everyone but I do have a dedicated fat32 card for homebrews.

**Comment by MAN-biker** [comment]
Tha SAME problem: "DRIVER INIT FAILED " error appears when i try to start any **MEGADRIVE** rom with pfba (4.4 Nintendo Switch and PSVita - the same trouble).
Many roms tested, compared by CRC using **gamelist_megadriv.xml**, renamed etc.
For example, **Bubble and Squeak (U) [!]**, CRC=28C4A006, **bubblesqu.zip**
