### ISSUE TITLE
pFBA remapping controls also remaps UI actions

### ISSUE THREAD

**Issue by jskuby** [Cpasjuste/pemu#5]
Using on the switch, I changed the order of my face buttons for games and it also changed the menu actions like selecting and adding to favorites. Alone this isn’t much of an issue however the theme shows the original button mapping which no longer match the reconfigured mapping.

**Comment by Cpasjuste** [comment]
Hi, thanks for the report. This has been fixed in c833ada86807956d1c75eb48843fe330a123af3d and will be available soon.
