### ISSUE TITLE
psnes4.4 can't  reset game ,Far East of Eden ? need this operate

### ISSUE THREAD

**Issue by jjslshn** [Cpasjuste/pemu#50]
thinks Cpasjuste

**Comment by Cpasjuste** [comment]
Hi,

I don't understand your problem, can you be more explicit ?

**Comment by jjslshn** [comment]
e,thinks 。the game FarEastofEdenZero  run fist will require reset Twice。 psnes doesn't own this operate function，or i doesn't find how to do this

**Comment by jjslshn** [comment]
https://cdromance.com/snes-rom/far-east-of-eden-zero-english-patched/         the rom.  run it fist time ,will require check rom ,then  require  reset the game . (need like snes9x1.6  PC ,the reset option on menu )

**Comment by Cpasjuste** [comment]
Hi,

I'm sorry but I won't support special cases like this.
