### ISSUE TITLE
I can't see my roms in psne 4.4

### ISSUE THREAD

**Issue by kryzv** [Cpasjuste/pemu#51]
Hi,

I can't see my roms to use PSNE.

I tried putting below into switch/psne/roms/ 

-No-Intro - Nintendo - Nintendo Entertainment System (2017-06-18).zip
-No-Intro - Nintendo - Nintendo Entertainment System (2017-06-18)
-all the roms zipped each
-all the roms each

Can you please help?
Thanks!

**Comment by Cpasjuste** [comment]
You should have each zipped roms in your "pnes" folder, not "psne". If you can't find a solution please use forums to get help!
