### ISSUE TITLE
Cannot Save State In Vita

### ISSUE THREAD

**Issue by OCracks** [Cpasjuste/pemu#56]
I open up the menu with start + select, go to states, then try to save by pressing x, but it just goes back to the game without filling up a slot

**Comment by OCracks** [comment]
This is for PSNES btw

**Comment by jariojose** [comment]
I think that is a problem with vita firmware version. I have the same problem. F.V.: 3.73

**Comment by OCracks** [comment]
Turns out the "save" folder didn't come with the release. Super easy for anyone to figure out really.
