### ISSUE TITLE
Previews error

### ISSUE THREAD

**Issue by Vaddum** [Cpasjuste/pemu#57]
Salut,

Juste pour information, sur pSNES 4.4 sur Switch (testé sous SXOS 3.0.0 et 3.0.2 beta) au bout d'un certain temps les previews disparaissent. Après redémarrage du homebrew, tout redevient normal.

Autrement, vous le savez certainement déjà, mais l'icone du homebrew et un carré bleu tout moche.

Merci pour ce superbe émulateur de qualité à l'interface épurée et bien pensée !

**Comment by Cpasjuste** [comment]
Bonjour,

Il me semble que ces problèmes sont réglés sur les dernières versions. Si ce n'est pas le cas, merci de commenter ici !
