### ISSUE TITLE
Add file browser?

### ISSUE THREAD

**Issue by juliancallan** [Cpasjuste/pemu#58]
Any chance of a browser just to navigate to ROMs? Would be much handier for the Vita as I keep all my ROMs for various emulators in one big folder on ux:0
Thanks!

**Comment by clort81** [comment]
On the OpenPandora build from repo 6332397 Jul 27 14:49 psnes_ptitseb.pnd   

I just get a window with blue, green and red fields.  No way to open a file. 

+ for Main menu and - for Rom menu (plus and minus on keyboard) have no effect.

Also it's listed as 'PNES' in menu, not 'PSNES'.  But the running emulator says PSNES.

**Comment by Cpasjuste** [comment]
Hi,

This is not planned, sorry !
