### ISSUE TITLE
Saving state in pfba on vita causes a crash

### ISSUE THREAD

**Issue by Stajin** [Cpasjuste/pemu#59]
When saving state, as soon as I click OK to verify I want to save the state it immediately causes a crash.

**Comment by renatotec** [comment]
I can confirm this on mine too, v4.4 on 3.60 firmware

**Comment by renatotec** [comment]
> When saving state, as soon as I click OK to verify I want to save the state it immediately causes a crash.

I can confirm this on mine too, v4.4 on 3.60 firmware

**Comment by fabinhojcr** [comment]
This problem also happens to me in v4.4 in ps vita firmware 3.73

**Comment by glisteningly** [comment]
This problem also happens to me in v4.4 in ps vita firmware 3.65 with tf card adapter

**Comment by whmzsu** [comment]
This problem also happens to me in v4.4 in ps vita firmware 3.60 with tf card adapter

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
