### ISSUE TITLE
Forgotten Worlds (CPS1) Crashes Switch

### ISSUE THREAD

**Issue by chr0m** [Cpasjuste/pemu#6]
Attempting to load Forgotten Worlds crashes the Switch and forces Atmosphere to reboot.

**Comment by Winklepicker** [comment]
I have tested this, but I am on "SX OS", no crashes.  Looks likes its "Atmosphere OS" related.

**Comment by chr0m** [comment]
Hmm, that is odd. I just tried on SXOS and it crashes that too.

Maybe it's my rom set, but I built it using the dats here:
https://github.com/libretro/fbalpha/tree/master/dats

**Comment by Winklepicker** [comment]
Which version/name of the rom are you using? What file system is your switch on? fat32 or exfat? 
If your using "exfat" I'd recommend changing to "fat32"

**Comment by chr0m** [comment]
I tried the parent and several clones.

Rebuilt using latest FBA dat from libretro github using clrmamepro.

Also tried using the versions from the latest mame (0.208)

I'm using fat32.

**Comment by Cpasjuste** [comment]
Hi, this is now fixed in 6bc8a46fdbd3097e4d31290c64f4f48d0750357b, will be released soon.
