### ISSUE TITLE
Psnes - Switch - Error loading save state from Version 304 into the version 404.

### ISSUE THREAD

**Issue by roberutokdo** [Cpasjuste/pemu#62]
Hello guys, I was playing the SNES game called Chrono Trigger on my switch which had the Psnes 304 version before Nintendo OS update to 10.1.0 which is forcing to use the Psnes version 404. 

So my question is: Is that possible to use the same save state?

If it doesn't, how can I convert the old save state to use it into the new Psnes version?

Into the attachment, I uploaded the save state from the old version.

[saves.zip](https://github.com/Cpasjuste/pemu/files/5011421/saves.zip)

Thanks.

**Comment by Cpasjuste** [comment]
Hi, sorry for the (very very) late reply. This is should now be fixed .
