### ISSUE TITLE
pfba-v4 launch crash on switch [Firmware 10.1.0] [Atomsphere 0.14.1]

### ISSUE THREAD

**Issue by asingingfish** [Cpasjuste/pemu#66]
When I use pfba 4.x, it can't launch and show crash error just like the image.

but, the 3.x version is well...

![微信图片_20200902222805](https://user-images.githubusercontent.com/14145640/91996470-97a9e980-ed6b-11ea-8bf3-246a04980896.jpg)

**Comment by Cpasjuste** [comment]
This is now fixed, closing.
