### ISSUE TITLE
pFBN 4.4 important issue about stick direction bug in flip mode

### ISSUE THREAD

**Issue by skylow1** [Cpasjuste/pemu#68]
In order to play vertical game such as 1942, Strikers 1945, etc in flip mode,
I want to rotate analog stick direction as well as screen.
But pFBN does not support rotation mode of analog stick or digital pad toward 90 degree or 270 degree,
So, I have to manually config the direction keys for those vertical games like up->right, down->left, right->up, left->down.

However, the problem is that even if I manually change the stick direction keys, the direction moves diagonally in the actual game. The reason I thought is that it seems to recognize the input as duplicated at the same time as the default direction keys in the device regardless of the direction keys that I manually entered.
Please be sure to fix this error. It is almost impossible to play the game normally because of this bug.

**Comment by lineacero** [comment]
Please error 1942,1945 please

**Comment by Cpasjuste** [comment]
Hi,

I think this should be fixed in [version 6.0](https://github.com/Cpasjuste/pemu/releases/tag/v6.0), can you confirm this ?

**Comment by Cpasjuste** [comment]
Hi, should be fixed in [6.2](https://github.com/Cpasjuste/pemu/releases/tag/v6.2) (currently building, files will be available soon). If not, be sure to report here and i'll re-open the issue.
