### ISSUE TITLE
Missing dependancies for compilation

### ISSUE THREAD

**Issue by wally4000** [Cpasjuste/pemu#72]
Doing a compile for the Dragonbox Pyra and found these libs were missing at link

[ 29%] Linking CXX executable pnes
/usr/bin/ld: cannot find -lass (libass-dev) 
/usr/bin/ld: cannot find -lbz2 (libbz2-dev)
/usr/bin/ld: cannot find -lfribidi

:)

**Comment by Cpasjuste** [comment]
I won't support other platforms, you need to fix this yourself, sorry.

**Comment by wally4000** [comment]
This is just Debian Linux on ARM :-)
