### ISSUE TITLE
pFBN support preview images and videos can't download the link.

### ISSUE THREAD

**Issue by parkjungja** [Cpasjuste/pemu#74]
Click the link, and the server appears to be shut down.

It's 404 not found.

Please upload it again.

**Comment by Cpasjuste** [comment]
Hi,

Thanks for the report, this is a major issue. I'll try to fix that tomorrow, or next week at worst.

**Comment by lineacero** [comment]
Yessss

**Comment by Cpasjuste** [comment]
Thanks, fixed !
