### ISSUE TITLE
No Open the ROMS after a video

### ISSUE THREAD

**Issue by HectorHugo170031** [Cpasjuste/pemu#75]
If the system play the video of a game then the videogame doesn't start.

**Comment by Panja0** [comment]
I already addressed this issue months ago. 
Have a look here:
https://github.com/Cpasjuste/pemu/issues/52

**Comment by HectorHugo170031** [comment]
> I already addressed this issue months ago.
> Have a look here:
> #52

Thank you so much for the answer and the information.
:D

**Comment by Panja0** [comment]
No problem at all!
I don’t think it’ll be fixed soon though... 😒
