### ISSUE TITLE
Pnes psvita

### ISSUE THREAD

**Issue by lineacero** [Cpasjuste/pemu#76]
I would like to make a request to @cpasjuste ,,, Pnes for Psvita would be a really good gem.

**Comment by Yoti** [comment]
+1

**Comment by Yoti** [comment]
+1

@Cpasjuste may you add pNES 4.4 for PS Vita?

**Comment by lineacero** [comment]
Please,,please,yes

**Comment by 1alien1** [comment]
same here. i actually read on another site that it should be already available so i was surprised to not find it here? or am i missing something?

**Comment by Cpasjuste** [comment]
Hi, this should be working fine in latest release: https://github.com/Cpasjuste/pemu/releases/tag/v5.2
Please report here if this is not the case!
