### ISSUE TITLE
[Question] Is there a way to change the "modifier" keys?

### ISSUE THREAD

**Issue by Panja0** [Cpasjuste/pemu#78]
At the moment when you're in game you need to press (-) and (+) on the controller to bring up the (emulation) options menu.
Is there a way to change that combination? I have a 8bitdo SN30 GP controller and I have to use (select) and (start) but the select button is also used (with dpad down) to use as the home button. So bringing up the (emulation) options menu is not possible with this controller.

**Comment by lineacero** [comment]
Please,yes,,please
