### ISSUE TITLE
When will release an latest version of pFBN

### ISSUE THREAD

**Issue by mzy1996** [Cpasjuste/pemu#79]
I had seen the last version of pFBN v4.4 was release on 13 May 2020.It has been so long since the last version released,so when will the v4.5 or higher version released?

**Comment by mzy1996** [comment]
I am using PSVita Version of pFBN

**Comment by lineacero** [comment]
please 4.5 and Virtual keyboard for spectrum emulator and vertical games correction arcade stick please
