### ISSUE TITLE
pSNES 3.1 game rom "Coolworld" causes switch to crash when you start game

### ISSUE THREAD

**Issue by Winklepicker** [Cpasjuste/pemu#8]
Found a strange issue, 

I tried both the "europe" and "US" version of roms, using SX OS. The game starts, but when you press "start game" it causes the switch to crash.

**Comment by Cpasjuste** [comment]
Hi, thanks for the report! This have been fixed in 309b1b1eac28caef26698153907ea29b53dab83f, will be released soon.
