### ISSUE TITLE
Nes and megadriv  slow on pfba   psv platfrom .

### ISSUE THREAD

**Issue by whmzsu** [Cpasjuste/pemu#80]
Nes and megadriv  slow on pfba   psv platfrom .
Is it the currentyly normal state on pfba 4.4 psv ???

**Comment by Cpasjuste** [comment]
Hi, this should be fixed (as possible as it can) in latest versions, closing.

**Comment by whmzsu** [comment]
> Hi, this should be fixed (as possible as it can) in latest versions, closing.

Thanks , I will have a test on the latest version.
