### ISSUE TITLE
pSNES psvita could not save game states

### ISSUE THREAD

**Issue by ygnid** [Cpasjuste/pemu#82]
Neither in game save or by emulator, save doesn't work at all, no game save files are created. Is this a common problem or just my vita?

**Comment by elegido22** [comment]
Hi, i have the same problem but in [pgen.vpk](https://github.com/Cpasjuste/pemu/releases/download/v6.2/pgen.vpk), i can't save games. 

I have the folder ux0:data/psgen/saves/

I don't see on any config file the savedata folder to tell the system to save there  the files

**Comment by Cpasjuste** [comment]
Hi, all is fixed and will be available in next release.
