### ISSUE TITLE
box2d config file not found

### ISSUE THREAD

**Issue by nmchlngy4** [Cpasjuste/pemu#87]
Good day, everyone.

I am attempting to compile pemu (specifically pnes) for the PlayStation Vita, and I am stuck at the box2d file not being found by CMake.

I did try to install libbox2d on my Ubuntu 20.04 setup, but I got this instead:

```
-- C2D: target platform: vita, cmake version: 3.16.3
-- C2D: Ps Vita with Gxm support enabled
CMake Error at libcross2d/CMakeLists.txt:168 (find_package):
  By not providing "Findbox2d.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "box2d", but
  CMake did not find one.

  Could not find a package configuration file provided by "box2d" with any of
  the following names:

    box2dConfig.cmake
    box2d-config.cmake

  Add the installation prefix of "box2d" to CMAKE_PREFIX_PATH or set
  "box2d_DIR" to a directory containing one of the above files.  If "box2d"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Any help would be appreciated.

**Comment by lineacero** [comment]
Yes please,,pemu psvita,,please,please

**Comment by Cpasjuste** [comment]
Hi,

You need a recent version on box2d installed (compiled and installed from source). But you "should" be able to compile it with "-DOPTION_BOX2D=OFF" cmake option.

**Comment by lineacero** [comment]
nmchlngy4 It would be wonderful if you compiled it friend, it would be great to have the Pnes for Psvita please.

**Comment by Cpasjuste** [comment]
There's no pnes releases because it is very slow on the vita. I guess nestopia is to heavy for it. 
I may try to take another look someday but my time is very limited right now!

**Comment by Cpasjuste** [comment]
Hi,

I just updated the (master) repo, and pnes should compile on vita with this options (and with TinyXML2 installed from [here](https://github.com/Cpasjuste/packages/tree/TinyXML2)):

`-DPLATFORM_VITA=ON -DOPTION_BUILTIN_MINIZIP=ON -DMPV_PLAYER=OFF`

Please note that the skin is not up to date, it may cause some problems. I fast/ugly fix could be to copy a skin from pfba which is more up to date.

**Comment by lineacero** [comment]
Yes.yes,thanks,,

**Comment by lineacero** [comment]
Buenas nmchlngy4 ya tienes la piel para Pnes psvita?

**Comment by nmchlngy4** [comment]
Okay, I'll try when I have time. Unfortunately, I am a very busy person, so it will come later than expected.

**Comment by lineacero** [comment]
When you can make it clear
There are many people that you manage to make happy if you publish it on gbatemp for the whole community and I congratulate you.
