### ISSUE TITLE
Question about previews

### ISSUE THREAD

**Issue by Corshi** [Cpasjuste/pemu#89]
How ware previews generated?
I have over 200 roms that ware translated from JP to EN and I would like them to fit, to the rest of the roms.

**Comment by Cpasjuste** [comment]
Hi,

Previews (and databases files) are downloaded with [sscrap](https://github.com/Cpasjuste/sscrap). To add new games it's a little tricky... but you may be able to download gamelists [here](https://github.com/Cpasjuste/pemu/tree/master/pfbneo/data/common/romfs), edit then put in your "data" folder ("/switch/pfba" for switch, "/data/pfba" for ps4, etc..). This should override defaults one.
