### ISSUE TITLE
pFBA - v3.3 The romlist shows "48k spectrum games" 

### ISSUE THREAD

**Issue by Winklepicker** [Cpasjuste/pemu#9]
Issue when browsing the rom list, 

"48k spectrum" game entries are seen as green "working" in the roms list (even when not installed on switch).  Currently no way to hide them or remove them from the list.

**Comment by Cpasjuste** [comment]
I guess you have them in the "msx" folder, which is the right way to add them as stated in the readme (https://github.com/Cpasjuste/pemu/tree/master/pfba) ? Because i don't have this problem here.

**Comment by Cpasjuste** [comment]
Hi, i think it should be fixed now: 7c40097e1d7829285c187b764d17c54901fd54d8

**Comment by Cpasjuste** [comment]
This is now really fixed in 4442d2d501de68b16dbb9b6451d8a9e8f7057a85, will be available soon :)
