### ISSUE TITLE
Please add CRT GEOM Flat

### ISSUE THREAD

**Issue by s3m80** [Cpasjuste/pemu#91]
I really like the CRT GEOM on your emulator but not on geom profile please add crt geom flat editiion. thank you so much

**Comment by lineacero** [comment]
Yeahhhhhhhh crt geom

**Comment by s3m80** [comment]
no no I mean crt geom but flat no curvature on the screen

**Comment by Cpasjuste** [comment]
Hi, this was [just added](4dae02ca8f123e96eab4a2a72165802956f0d417), will try to do a release asap (may take a few weeks).

**Comment by s3m80** [comment]
> Hi, this was just added ([4dae02c](https://github.com/Cpasjuste/pemu/commit/4dae02ca8f123e96eab4a2a72165802956f0d417)), will try to do a release asap (may take a few weeks).

thank you so much youre the best
