### ISSUE TITLE
Can you provide rom DATs for latest build?

### ISSUE THREAD

**Issue by tanaduda** [Cpasjuste/pemu#93]
Can you provide rom DATs for latest build?

**Comment by Cpasjuste** [comment]
Hi,

I updated pFBN [README.MD](https://github.com/Cpasjuste/pemu/blob/master/pfbneo/README.MD) with link to [current DATs files](https://github.com/Cpasjuste/pemu/blob/master/pfbneo/README.MD).

**Comment by tanaduda** [comment]
Thanks for your efforts!!
