### ISSUE TITLE
Language garbled

### ISSUE THREAD

**Issue by asdone7** [Cpasjuste/pemu#98]
hello，
I translated some other languages for pfbn and gamelist, but the compiled code is garbled. What should I do？

That's all. Thank you！

**Comment by Cpasjuste** [comment]
Hi,

What do you mean by "garbled" ? If the text is utf-8 or something it is not actually supported.

**Comment by asdone7** [comment]
Hello，
Thank you for your reply，I translated the `"default options"` part of `"c2dui_config.cpp"` and the game name in `gamelist.xml` ，the translated text cannot display content content after the build，by the way, I translated it into chinese，I am very regretful to see that you said it is actually not supported. Thank you again. I will continue to use the English version。

**Comment by Cpasjuste** [comment]
Yep sorry, I hope I'll add support for utf fonts in the future, but it will probably not come soon :/
