### ISSUE TITLE
Megadrive issues

### ISSUE THREAD

**Issue by tanaduda** [Cpasjuste/pemu#99]
Games like sf2 and ssf2 display “4x screen”...impossible to play

**Comment by Cpasjuste** [comment]
Hi,

Is this on switch or PS4 ?

**Comment by tanaduda** [comment]
Excuse me. PS4

**Comment by Cpasjuste** [comment]
Hi, this is fixed in commit 8899a4401d8a6b199f9870530cebe21e5eeecedb, will be available for next release.

**Comment by tanaduda** [comment]
Thanks!!!!
